### ISSUE TITLE
An error occured during polling state on v5.0.15 

### ISSUE THREAD

**Issue by iggups** [SeydX/homebridge-fritz-platform#136]
**Describe the bug**
After updating to version v5.0.15 and restarting Homebridge I get the following log output:

```
[27.11.2020, 09:37:17] [FritzPlatform] Smarthome: An error occured during polling state (smarthome)
[27.11.2020, 09:37:17] [FritzPlatform] TypeError: Cannot read property '$' of undefined
    at /usr/local/lib/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:3013:20
    at Array.map (<anonymous>)
    at refreshSmarthome (/usr/local/lib/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:3002:40)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2784:5)
```

I enabled `debug` but there's no additional context than with `debug` disabled. I'm running a few outlet switches as well as some thermostats.

```
Node.js Version v14.15.0
Npm Version v6.14.8
Homebridge 1.1.6
```

Let me know if you need some additional information :slightly_smiling_face:

**Comment by cschildhorn** [comment]
Same here.

![A4230302-6C41-46FA-9786-861E62A83068](https://user-images.githubusercontent.com/516532/100431708-d2849a80-3098-11eb-8a79-49a6ba3ddc90.jpeg)

**Comment by tooh** [comment]
Same here

**Comment by mbounine** [comment]
I can confirm.

**Comment by SeydX** [comment]
Sry guys, fixed in v5.0.16

**Comment by FritzFox** [comment]
Meine FRITZ!Box Steckdosen fungieren als Frost Waechter. Die Homepage ist nur dafür da, um die Temperatur an zu zeigen und um zu sehen, ob und wann geschaltet wird. Ich kenne mich leider nicht besonders gut aus. Nachdem diese Meldung hier aufgetaucht sind, lässt sich die Homepage nicht mehr im Browser aufrufen. Ich muss den Stecker ziehen und neu starten. Das ganze passiert einmal am Tag. Vielleicht kann mir jemand helfen, ich würde mich sehr freuen. LG

[20/12/2022, 14:56:57] [FritzPlatform] An error occurred during polling smarthome devices!
[20/12/2022, 14:56:57] [FritzPlatform] Error: connect ENETUNREACH 192.168.188.1:49443 - Local (0.0.0.0:0)
    at Object.exports.request (/var/lib/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:103:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at exports.requestXml (/var/lib/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:230:20)
    at Service.execAction (/var/lib/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Fritzbox.getSmarthomeDevices (/var/lib/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:222:22)
    at Handler.poll (/var/lib/homebridge/node_modules/homebridge-fritz-platform/src/accessories/smarthome/smarthome.handler.js:1755:28) {
  title: 'No Response',
  code: 'ENETUNREACH',
  soap: {
    action: 'urn:dslforum-org:service:DeviceConfig:1#X_AVM-DE_CreateUrlSID'
  },
  url: 'https://Hello:p%5D0sQ,n1k%3D(7B@192.168.188.1:49443/upnp/control/deviceconfig'
}
[20/12/2022, 14:57:12] [FritzPlatform] An error occurred during polling smarthome devices!
[20/12/2022, 14:57:12] [FritzPlatform] Error: connect ENETUNREACH 192.168.188.1:49443 - Local (0.0.0.0:0)
    at Object.exports.request (/var/lib/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:103:21)
