### ISSUE TITLE
Since Fritz Box Update to Version 07.24-86841 BETA  Log is full of Error Messages

### ISSUE THREAD

**Issue by ash123-germany** [SeydX/homebridge-fritz-platform#162]
**Describe the bug**
I updated my Fritz Box 6591 with Version 7.24              (sorry im NEW in this Homebridge Topic)
Since then i got i log :
9.3.2021, 23:37:57 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:37:57 [Fritz-Box] FritzBox Wifi guest: Could not process the request during polling state (wifi_guest)
9.3.2021, 23:37:57 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:37:57 [Fritz-Box] FritzBox Lock: Could not process the request during polling state (lock)
9.3.2021, 23:37:57 [Fritz-Box] FritzBox Led: Polling state (led)...
9.3.2021, 23:37:57 [Fritz-Box] FritzBox Led: Could not process the request during polling state (led)
9.3.2021, 23:37:57 [Fritz-Box] Smarthome: Could not process the request during polling state (smarthome)
9.3.2021, 23:38:07 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:38:07 [Fritz-Box] FritzBox Wifi guest: Could not process the request during polling state (wifi_guest)
9.3.2021, 23:38:07 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:38:07 [Fritz-Box] FritzBox Lock: Could not process the request during polling state (lock)
9.3.2021, 23:38:07 [Fritz-Box] FritzBox Led: Polling state (led)...
9.3.2021, 23:38:07 [Fritz-Box] FritzBox Led: Could not process the request during polling state (led)
9.3.2021, 23:38:07 [Fritz-Box] Smarthome: Could not process the request during polling state (smarthome)
9.3.2021, 23:38:17 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:38:17 [Fritz-Box] FritzBox Wifi guest: Could not process the request during polling state (wifi_guest)
9.3.2021, 23:38:17 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:38:17 [Fritz-Box] FritzBox Lock: Could not process the request during polling state (lock)
9.3.2021, 23:38:17 [Fritz-Box] FritzBox Led: Polling state (led)...
9.3.2021, 23:38:17 [Fritz-Box] FritzBox Led: Could not process the request during polling state (led)
9.3.2021, 23:38:18 [Fritz-Box] Smarthome: Could not process the request during polling state (smarthome)
9.3.2021, 23:38:28 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:38:28 [Fritz-Box] FritzBox Wifi guest: Could not process the request during polling state (wifi_guest)
9.3.2021, 23:38:28 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:38:28 [Fritz-Box] FritzBox Lock: Could not process the request during polling state (lock)
9.3.2021, 23:38:28 [Fritz-Box] FritzBox Led: Polling state (led)...
9.3.2021, 23:38:28 [Fritz-Box] FritzBox Led: Could not process the request during polling state (led)
9.3.2021, 23:38:28 [Fritz-Box] Smarthome: Could not process the request during polling state (smarthome)
9.3.2021, 23:38:38 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:38:38 [Fritz-Box] FritzBox Wifi guest: Could not process the request during polling state (wifi_guest)
9.3.2021, 23:38:38 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:38:38 [Fritz-Box] FritzBox Lock: Could not process the request during polling state (lock)
9.3.2021, 23:38:38 [Fritz-Box] FritzBox Led: Polling state (led)...
9.3.2021, 23:38:38 [Fritz-Box] FritzBox Led: Could not process the request during polling state (led)
9.3.2021, 23:38:38 [Fritz-Box] Smarthome: Could not process the request during polling state (smarthome)
9.3.2021, 23:38:48 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:38:48 [Fritz-Box] FritzBox Wifi guest: Could not process the request during polling state (wifi_guest)
9.3.2021, 23:38:48 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:38:48 [Fritz-Box] FritzBox Lock: Could not process the request during polling state (lock)
9.3.2021, 23:38:48 [Fritz-Box] FritzBox Led: Polling state (led)...
9.3.2021, 23:38:48 [Fritz-Box] FritzBox Led: Could not process the request during polling state (led)
9.3.2021, 23:38:48 [Fritz-Box] Smarthome: Could not process the request during polling state (smarthome)
9.3.2021, 23:38:58 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:38:58 [Fritz-Box] FritzBox Wifi guest: Could not process the request during polling state (wifi_guest)
9.3.2021, 23:38:58 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:38:58 [Fritz-Box] FritzBox Lock: Could not process the request during polling state (lock)
9.3.2021, 23:38:58 [Fritz-Box] FritzBox Led: Polling state (led)...
9.3.2021, 23:38:58 [Fritz-Box] FritzBox Led: Could not process the request during polling state (led)
9.3.2021, 23:38:58 [Fritz-Box] Smarthome: Could not process the request during polling state (smarthome)
9.3.2021, 23:39:08 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:39:08 [Fritz-Box] FritzBox Wifi guest: Could not process the request during polling state (wifi_guest)
9.3.2021, 23:39:08 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:39:08 [Fritz-Box] FritzBox Lock: Could not process the request during polling state (lock)
9.3.2021, 23:39:08 [Fritz-Box] FritzBox Led: Polling state (led)...
9.3.2021, 23:39:08 [Fritz-Box] FritzBox Led: Could not process the request during polling state (led)
9.3.2021, 23:39:08 [Fritz-Box] Smarthome: Could not process the request during polling state (smarthome)
9.3.2021, 23:39:18 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:39:18 [Fritz-Box] FritzBox Wifi guest: Could not process the request during polling state (wifi_guest)
9.3.2021, 23:39:18 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:39:18 [Fritz-Box] FritzBox Lock: Could not process the request during polling state (lock)
9.3.2021, 23:39:18 [Fritz-Box] FritzBox Led: Polling state (led)...
9.3.2021, 23:39:18 [Fritz-Box] FritzBox Led: Could not process the request during polling state (led)
9.3.2021, 23:39:18 [Fritz-Box] Smarthome: Could not process the request during polling state (smarthome)
9.3.2021, 23:39:28 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:39:28 [Fritz-Box] FritzBox Wifi guest: Could not process the request during polling state (wifi_guest)
9.3.2021, 23:39:28 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:39:28 [Fritz-Box] FritzBox Lock: Could not process the request during polling state (lock)
9.3.2021, 23:39:28 [Fritz-Box] FritzBox Led: Polling state (led)...
9.3.2021, 23:39:28 [Fritz-Box] FritzBox Led: Could not process the request during polling state (led)
9.3.2021, 23:39:28 [Fritz-Box] Smarthome: Could not process the request during polling state (smarthome)
9.3.2021, 23:39:38 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:39:38 [Fritz-Box] FritzBox Wifi guest: Could not process the request during polling state (wifi_guest)
9.3.2021, 23:39:38 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:39:38 [Fritz-Box] FritzBox Lock: Could not process the request during polling state (lock)
9.3.2021, 23:39:38 [Fritz-Box] FritzBox Led: Polling state (led)...
9.3.2021, 23:39:38 [Fritz-Box] FritzBox Led: Could not process the request during polling state (led)
9.3.2021, 23:39:38 [Fritz-Box] Smarthome: Could not process the request during polling state (smarthome)
9.3.2021, 23:39:48 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:39:48 [Fritz-Box] FritzBox Wifi guest: Could not process the request during polling state (wifi_guest)
9.3.2021, 23:39:48 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:39:49 [Fritz-Box] FritzBox Lock: Could not process the request during polling state (lock)
9.3.2021, 23:39:49 [Fritz-Box] FritzBox Led: Polling state (led)...
9.3.2021, 23:39:49 [Fritz-Box] FritzBox Led: Could not process the request during polling state (led)
9.3.2021, 23:39:49 [Fritz-Box] Smarthome: Could not process the request during polling state (smarthome)
9.3.2021, 23:39:59 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:39:59 [Fritz-Box] FritzBox Wifi guest: An error occured during polling state (wifi_guest)
9.3.2021, 23:39:59 [Fritz-Box] Error: Invalid response: 401:Unauthorized
    at Request._callback (/home/hoobs/.hoobs/node_modules/@seydx/fritzbox/src/lib/request.ts:30:13)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
9.3.2021, 23:39:59 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:39:59 [Fritz-Box] FritzBox Lock: An error occured during polling state (lock)
9.3.2021, 23:39:59 [Fritz-Box] Error: Invalid response: 401:Unauthorized
    at Request._callback (/home/hoobs/.hoobs/node_modules/@seydx/fritzbox/src/lib/request.ts:30:13)
    at Request.self.callback (/home/hoobs/.hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/hoobs/.hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1327:12)

9.3.2021, 23:38:58 [Fritz-Box] Smarthome: Could not process the request during polling state (smarthome)
9.3.2021, 23:39:08 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:39:08 [Fritz-Box] FritzBox Wifi guest: Could not process the request during polling state (wifi_guest)
9.3.2021, 23:39:08 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:39:08 [Fritz-Box] FritzBox Lock: Could not process the request during polling state (lock)
9.3.2021, 23:39:08 [Fritz-Box] FritzBox Led: Polling state (led)...
9.3.2021, 23:39:08 [Fritz-Box] FritzBox Led: Could not process the request during polling state (led)
9.3.2021, 23:39:08 [Fritz-Box] Smarthome: Could not process the request during polling state (smarthome)
9.3.2021, 23:39:18 [Fritz-Box] FritzBox Wifi guest: Polling state (wifi_guest)...
9.3.2021, 23:39:18 [Fritz-Box] FritzBox Wifi guest: Could not process the request during polling state (wifi_guest)
9.3.2021, 23:39:18 [Fritz-Box] FritzBox Lock: Polling state (lock)...
9.3.2021, 23:39:18 [Fritz-Box] FritzBox Lock: Could not process the request during polling state (lock)
9.3.2021, 23:39:18 [Fritz-Box] FritzBox Led: Polling state (led)...

**To Reproduce**
 Install version 7.24 on Fritz box and go in log

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: [Iphone 12]
 - OS: [ios14]
 - Browser [safari]
 - Version [?]

**Additional context**
I do not know what i can do ?

My config Jason for Fritz Box:

       {
            "platform": "FritzPlatform",
            "devices": [
                {
                    "tr064": true,
                    "options": {
                        "broadband": "characteristic",
                        "wifi_guest": "switch",
                        "lock": "switch",
                        "led": "switch",
                        "aw": "characteristic",
                        "wps": "characteristic"
                    },
                    "connection": "dsl",
                    "ssl": true,
                    "serialNumber": "12345",
                    "username": "XXXXXX",
                    "manufacturer": "Fritz Box",
                    "igd": true,
                    "master": true,
                    "port": 49000,
                    "hide": true,
                    "host": "192.168.178.1",
                    "password": "XXXXXXXX",
                    "readOnly": false,
                    "name": "FritzBox",
                    "model": "6591"
                }
            ],
            "telegram": {
                "active": false,
                "messages": {
                    "presence": {},
                    "callmonitor": {},
                    "alarm": {},
                    "reboot": {},
                    "network": {}
                }
            },
            "callmonitor": {
                "port": 1012,
                "active": false,
                "incomingTo": [],
                "outgoingFrom": []
            },
            "wol": [
                {
                    "address": "XXXXXXXXXXX",
                    "name": "Computer"
                }
            ],
            "smarthome": [
                {
                    "ain": "XXXXXXXXXXXXXX",
                    "accType": "temperature",
                    "name": "DECT 100 Temperature"
                }
            ],
            "name": "Fritz-Box",
            "options": {
                "polling": {
                    "timer": 10,
                    "exclude": []
                },
                "presence": {},
                "reboot": {}
            },
            "plugin_map": {
                "plugin_name": "homebridge-fritz-platform"
            },
            "extras": {
                "alarm": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "wakeup": {
                    "active": false
                },
                "phoneBook": {
                    "active": false,
                    "blacklists": []
                }
            },
            "debug": true,
            "presence": [],
            "network": []
        },

**Comment by ash123-germany** [comment]
OK found the Problem
 
in fritz box from former versions the USERNAME which i entered was always ADMIN.

But wirh Fritz Box Version 7.24 they create a new  user:

fxxxxxxxxx
automatisch angelegt
Benutzer zum FRITZ!Box-Kennwort

Found under  "Fritzbox Setting" "SYSTEM" "FRIT!BOX-BENUTZER"  if i enter this name as "username": "XXXXXX",

ALL WORKS FINE AGAIN.
