### ISSUE TITLE
Fritz!DECT 200 switch broken after last update

### ISSUE THREAD

**Issue by CSchmidtDD** [SeydX/homebridge-fritz-platform#184]
After updating to 5.1.0 on the homebridge I am unable to switch the actors on/off. 
Altough the current state will be correctly displayed, the switch action is not taking place. Neither in the Homebridge via the plugin actor nor the integration into Appe HomeKit one.

**Comment by SeydX** [comment]
Hey, what all can't you switch? And is there anything in log?

**Comment by CSchmidtDD** [comment]
Hey @SeydX, sorry for the missing info I forgot to put it in the original post.
I have looked through the Homebridge logs and enabled debug logging, please see the output:

`[5/26/2021, 11:50:56 AM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[5/26/2021, 11:50:56 AM] [HB Supervisor] Started Homebridge v1.3.4 with PID: 521
Initializing HAP-NodeJS v0.9.4...
[5/26/2021, 11:50:58 AM] Loaded config.json with 1 accessories and 4 platforms.
[5/26/2021, 11:50:59 AM] Loaded 17 cached accessories from cachedAccessories.
[5/26/2021, 11:50:59 AM] ---
...
[5/26/2021, 11:51:01 AM] ---
[5/26/2021, 11:51:01 AM] Loaded plugin: homebridge-fritz-platform@5.1.0
[5/26/2021, 11:51:04 AM] Registering platform 'homebridge-fritz-platform.FritzPlatform'
[5/26/2021, 11:51:04 AM] ---
...
[5/26/2021, 11:51:14 AM] [Fritz] FritzBox Wifi guest: Configuring accessory...
[5/26/2021, 11:51:14 AM] [Fritz] PC Stecki: Configuring accessory...
[5/26/2021, 11:51:14 AM] [Fritz] PC Stecki Temperature: Configuring accessory...
[5/26/2021, 11:51:14 AM] [Fritz] Stecki: Configuring accessory...
[5/26/2021, 11:51:14 AM] [Fritz] Stecki Temperature: Configuring accessory...
[5/26/2021, 11:51:14 AM] [Fritz] Christoph: Configuring accessory...
[5/26/2021, 11:51:14 AM] [Fritz] Conny: Configuring accessory...
[5/26/2021, 11:51:14 AM] [Fritz] NAS: Configuring accessory...
[5/26/2021, 11:51:14 AM] [Fritz] WoL: TurtleNAS: Configuring accessory...
[5/26/2021, 11:51:14 AM] [Fritz] WoL: TurtlePC: Configuring accessory...
[5/26/2021, 11:51:14 AM] [Fritz] Callmonitor: Configuring accessory...
[5/26/2021, 11:51:14 AM] [Fritz] PC: Configuring accessory...
[5/26/2021, 11:51:14 AM] [Fritz] Callmonitor connection established with 192.168.2.1:1012
[5/26/2021, 11:51:14 AM] [Fritz] FritzBox Wifi guest: Polling state (wifi_guest)...
[5/26/2021, 11:51:15 AM] [Fritz] FritzBox Wifi guest: An error occured during polling state (wifi_guest)
[5/26/2021, 11:51:15 AM] [Fritz] Error: Cannot reach FritzBox. No response received. (undefined)
    at Object.exports.request (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:54:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:67:20)
    at Service.execAction (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:130:20)
    at Fritzbox.getSecurityPort (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:189:20)
    at Fritzbox.upgradeSsl (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:198:18)
    at Fritzbox.initialize (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:60:7)
    at Fritzbox.exec (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:107:5)
    at get (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:865:22)
    at refreshDevices (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2422:15)
[5/26/2021, 11:51:15 AM] [Fritz] Hosts: An error occured during polling state (hosts)
[5/26/2021, 11:51:15 AM] [Fritz] Error: Cannot reach FritzBox. No response received. (undefined)
    at Object.exports.request (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:54:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:67:20)
    at Service.execAction (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:130:20)
    at refreshHosts (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2454:22)
    at Object.poll (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2391:5)
[5/26/2021, 11:51:15 AM] [TurtleBridge] TurtleBridge: 1 accessories
[5/26/2021, 11:51:15 AM] [Fritz] Smarthome: An error occured during polling state (smarthome)
[5/26/2021, 11:51:15 AM] [Fritz] Error: Cannot reach FritzBox. No response received. (undefined)
    at Object.exports.request (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:54:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:67:20)
    at Service.execAction (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:130:20)
    at refreshSmarthome (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2513:20)
    at Object.poll (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2392:5)
[5/26/2021, 11:51:15 AM] [TurtleBridge] masked debug info dumped to /homebridge/homebridge-hue.json.gz`

After the initial error on setup, it keeps pumping out the same errors shown, starting with polling wifi_guest as first accessory.
I double-checked the credentials, do you have an idea what could be the problem here?

**Comment by SeydX** [comment]
> Hey @SeydX, sorry for the missing info I forgot to put it in the original post.
> I have looked through the Homebridge logs and enabled debug logging, please see the output.
> 
> It seems, that all switches remain unfunctional, not only the DECT200 ones.
> 
> After the initial error on Start, it keeps pumping out the same errors shown, starting with polling wifi_guest as first accessory.
> I double-checked the credentials as well as the settings required in the installation instructions, do you have an idea what could be the problem here?
> 
> ```
> [5/26/2021, 11:50:56 AM] [HB Supervisor] Started Homebridge v1.3.4 with PID: 521
> Initializing HAP-NodeJS v0.9.4...
> [5/26/2021, 11:50:58 AM] Loaded config.json with 1 accessories and 4 platforms.
> [5/26/2021, 11:50:59 AM] Loaded 17 cached accessories from cachedAccessories.
> [5/26/2021, 11:50:59 AM] ---
> ...
> [5/26/2021, 11:51:01 AM] ---
> [5/26/2021, 11:51:01 AM] Loaded plugin: homebridge-fritz-platform@5.1.0
> [5/26/2021, 11:51:04 AM] Registering platform 'homebridge-fritz-platform.FritzPlatform'
> [5/26/2021, 11:51:04 AM] ---
> ...
> [5/26/2021, 11:51:14 AM] [Fritz] FritzBox Wifi guest: Configuring accessory...
> [5/26/2021, 11:51:14 AM] [Fritz] PC Stecki: Configuring accessory...
> [5/26/2021, 11:51:14 AM] [Fritz] PC Stecki Temperature: Configuring accessory...
> [5/26/2021, 11:51:14 AM] [Fritz] Stecki: Configuring accessory...
> [5/26/2021, 11:51:14 AM] [Fritz] Stecki Temperature: Configuring accessory...
> [5/26/2021, 11:51:14 AM] [Fritz] Christoph: Configuring accessory...
> [5/26/2021, 11:51:14 AM] [Fritz] Conny: Configuring accessory...
> [5/26/2021, 11:51:14 AM] [Fritz] NAS: Configuring accessory...
> [5/26/2021, 11:51:14 AM] [Fritz] WoL: TurtleNAS: Configuring accessory...
> [5/26/2021, 11:51:14 AM] [Fritz] WoL: TurtlePC: Configuring accessory...
> [5/26/2021, 11:51:14 AM] [Fritz] Callmonitor: Configuring accessory...
> [5/26/2021, 11:51:14 AM] [Fritz] PC: Configuring accessory...
> [5/26/2021, 11:51:14 AM] [Fritz] Callmonitor connection established with 192.168.2.1:1012
> [5/26/2021, 11:51:14 AM] [Fritz] FritzBox Wifi guest: Polling state (wifi_guest)...
> [5/26/2021, 11:51:15 AM] [Fritz] FritzBox Wifi guest: An error occured during polling state (wifi_guest)
> [5/26/2021, 11:51:15 AM] [Fritz] Error: Cannot reach FritzBox. No response received. (undefined)
>     at Object.exports.request (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:54:13)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at exports.requestXml (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:67:20)
>     at Service.execAction (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:130:20)
>     at Fritzbox.getSecurityPort (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:189:20)
>     at Fritzbox.upgradeSsl (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:198:18)
>     at Fritzbox.initialize (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:60:7)
>     at Fritzbox.exec (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:107:5)
>     at get (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:865:22)
>     at refreshDevices (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2422:15)
> [5/26/2021, 11:51:15 AM] [Fritz] Hosts: An error occured during polling state (hosts)
> [5/26/2021, 11:51:15 AM] [Fritz] Error: Cannot reach FritzBox. No response received. (undefined)
>     at Object.exports.request (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:54:13)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at exports.requestXml (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:67:20)
>     at Service.execAction (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:130:20)
>     at refreshHosts (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2454:22)
>     at Object.poll (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2391:5)
> [5/26/2021, 11:51:15 AM] [TurtleBridge] TurtleBridge: 1 accessories
> [5/26/2021, 11:51:15 AM] [Fritz] Smarthome: An error occured during polling state (smarthome)
> [5/26/2021, 11:51:15 AM] [Fritz] Error: Cannot reach FritzBox. No response received. (undefined)
>     at Object.exports.request (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:54:13)
>     at processTicksAndRejections (internal/process/task_queues.js:95:5)
>     at exports.requestXml (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:67:20)
>     at Service.execAction (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:130:20)
>     at refreshSmarthome (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2513:20)
>     at Object.poll (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2392:5)
> [5/26/2021, 11:51:15 AM] [TurtleBridge] masked debug info dumped to /homebridge/homebridge-hue.json.gz
> ```

 Can u install the beta version pls and post the log again after restart

`sudo npm i -g homebridge-fritz-platform@beta`

**Comment by SeydX** [comment]
@CSchmidtDD 

can u post your config.json pls

**Comment by CSchmidtDD** [comment]
@SeydX Thansk for your help

Here is the current config for homebridge and the plattform (slightly redacted):
```
{
    "bridge": {
	...
    },
    "accessories": [
        {
		...
        }
    ],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "auth": "none",
            "theme": "auto",
            "tempUnits": "c",
            "lang": "de",
            "platform": "config"
        },
		...,
        {
            "name": "Fritz",
            "debug": false,
            "devices": [
                {
                    "name": "FritzBox",
                    "host": "192.168.2.1",
                    "username": "<secret>",
                    "password": "<secretPW>",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "master": true,
                    "readOnly": true,
                    "hide": true,
                    "connection": "repeater",
                    "options": {
                        "wifi_guest": "switch",
                        "wps": "characteristic"
                    }
                }
            ],
            "presence": [
                {
                    "active": true,
                    "blockTelegram": true,
                    "name": "<Name>",
                    "address": "192.168.2.10",
                    "accType": "occupancy",
                    "ping": false
                },
                {
                    "active": true,
                    "blockTelegram": true,
                    "name": "<Name2>",
                    "address": "192.168.2.13",
                    "accType": "occupancy",
                    "ping": false
                },
                {
                    "active": true,
                    "blockTelegram": false,
                    "name": "NAS",
                    "address": "192.168.2.2",
                    "accType": "occupancy",
                    "ping": false
                },
                {
                    "active": true,
                    "blockTelegram": false,
                    "name": "PC",
                    "address": "192.168.2.4",
                    "accType": "occupancy",
                    "ping": false
                },
                {
                    "active": true,
                    "blockTelegram": true,
                    "name": "<Name2> appliance",
                    "address": "192.168.2.21",
                    "accType": "occupancy",
                    "ping": false
                }
            ],
            "wol": [
                {
                    "name": "WoL: <Name>",
                    "address": "00:11:32:B5:4F:34"
                },
                {
                    "name": "WoL: <Name2>",
                    "address": "B4:2E:99:86:1B:9F"
                }
            ],
            "smarthome": [
                {
                    "name": "PC Stecki",
                    "ain": "<secret>",
                    "readOnly": false,
                    "energy": true,
                    "temperature": true,
                    "accType": "switch"
                },
                {
                    "name": "Stecki",
                    "ain": "<secret>",
                    "readOnly": false,
                    "energy": true,
                    "temperature": true,
                    "accType": "switch"
                }
            ],
            "callmonitor": {
                "active": true,
                "group": true,
                "ip": "192.168.2.1",
                "port": 1012
            },
            "extras": {
                "alarm": {
                    "active": false
                },
                "wakeup": {
                    "active": false
                },
                "ringlock": {
                    "active": false
                },
                "phoneBook": {
                    "active": false,
                    "accType": "switch"
                }
            },
            "options": {
                "presence": {
                    "anyone": false,
                    "accType": "occupancy"
                },
                "polling": {
                    "timer": 10
                }
            },
            "telegram": {
                "active": true,
                "token": "<secret>",
                "chatID": "<secret>",
                "messages": {
                    "presence": {
                        "user_in": "*Präsenz:* _@ ist da_",
                        "user_out": "*Präsenz:* _@ ist weg_",
                        "anyone_in": "*Präsenz:* _Jemand ist da_",
                        "anyone_out": "*Präsenz:* _Jemand ist weg_"
                    },
                    "callmonitor": {
                        "incoming": "*Anruf:* _von @_",
                        "outgoing": "*Anruf:* _an @_",
                        "disconnected": "_Aufgelegt_"
                    },
                    "reboot": {
                        "start": "*FritzBox* _startet sich neu_",
                        "finish": "*FritzBox* _ist wieder ereichbar_"
                    },
                    "network": {
                        "on": "*Netzwerk:* Detected _@_"
                    }
                }
            },
            "platform": "FritzPlatform"
        }
    ]
}

**Comment by CSchmidtDD** [comment]
Just tried 5.0.33 - everything works as intended when going back with the config.

I installed homebridge-fritz-platform v5.1.1-beta.2 and was of course met with the same error, now put in the port where you said in the config and restarted - now the same errormessages show up right before startup completion:

```
[5/28/2021, 2:45:04 PM] [Fritz] FritzBox Wifi guest: An error occured during polling state (wifi_guest)
[5/28/2021, 2:45:04 PM] [Fritz] Error: No or invalid response: http://192.168.2.1:49000/upnp/control/deviceinfo - URI malformed (undefined)
    at Object.exports.request (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:56:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:69:20)
    at Service.execAction (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:131:20)
    at Fritzbox.getSecurityPort (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:155:20)
    at Fritzbox.upgradeSsl (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:164:18)
    at Fritzbox.initialize (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:64:7)
    at Fritzbox.exec (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:110:5)
    at get (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:865:22)
    at refreshDevices (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2431:15)
[5/28/2021, 2:45:04 PM] [Fritz] Hosts: An error occured during polling state (hosts)
[5/28/2021, 2:45:04 PM] [Fritz] Error: No or invalid response: http://192.168.2.1:49000/upnp/control/hosts - URI malformed (undefined)
    at Object.exports.request (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:56:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:69:20)
    at Service.execAction (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:131:20)
    at refreshHosts (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2463:22)
    at Object.poll (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2400:5)
[5/28/2021, 2:45:05 PM] [Fritz] Smarthome: An error occured during polling state (smarthome)
[5/28/2021, 2:45:05 PM] [Fritz] Error: No or invalid response: http://192.168.2.1:49000/upnp/control/deviceconfig - URI malformed (undefined)
    at Object.exports.request (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:56:13)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:69:20)
    at Service.execAction (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:131:20)
    at refreshSmarthome (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2522:20)
    at Object.poll (/homebridge/node_modules/homebridge-fritz-platform/src/helper/deviceHandler.js:2401:5)
[5/28/2021, 2:45:05 PM] [TurtleBridge] masked debug info dumped to /homebridge/homebridge-hue.json.gz

**Comment by SeydX** [comment]
@CSchmidtDD 

can u try latest beta pls?

**Comment by CSchmidtDD** [comment]
Hi @SeydX 

Now it keeps crashing the homebridge at startup with this error:

```
[5/29/2021, 1:51:04 PM] [Fritz] Initializing FritzPlatform platform...
[5/29/2021, 1:51:08 PM] URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at new Fritzbox (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:38:25)
    at /homebridge/node_modules/homebridge-fritz-platform/src/platform.js:84:38
    at Array.map (<anonymous>)
    at new FritzPlatform (/homebridge/node_modules/homebridge-fritz-platform/src/platform.js:79:25)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
[5/29/2021, 1:51:08 PM] Got SIGTERM, shutting down Homebridge...
[5/29/2021, 1:51:09 PM] [TurtleBridge] TurtleBridge: 1 accessories
[5/29/2021, 1:51:09 PM] [TurtleBridge] masked debug info dumped to /homebridge/homebridge-hue.json.gz
[5/29/2021, 1:51:09 PM] Initializing platform accessory 'TurtleBridge'...
[5/29/2021, 1:51:09 PM] [TurtleBridge] TurtleBridge: 2 services
[5/29/2021, 1:51:13 PM] [TurtleBridge] goodbye
[5/29/2021, 1:51:13 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[5/29/2021, 1:51:18 PM] [HB Supervisor] Restarting Homebridge...
[5/29/2021, 1:51:18 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[5/29/2021, 1:51:19 PM] [HB Supervisor] Started Homebridge v1.3.4 with PID: 630
Initializing HAP-NodeJS v0.9.4...
[5/29/2021, 1:51:21 PM] Loaded config.json with 1 accessories and ... platforms.
[5/29/2021, 1:51:21 PM] Loaded 17 cached accessories from cachedAccessories.
[5/29/2021, 1:51:21 PM] ---
[5/29/2021, 1:51:23 PM] Warning: skipping plugin found at '/usr/local/lib/node_modules/homebridge-fritz-platform' since we already loaded the same plugin from '/homebridge/node_modules/homebridge-fritz-platform'.
[5/29/2021, 1:51:24 PM] Loaded plugin: homebridge-dyson-pure-cool@2.0.3
[5/29/2021, 1:51:24 PM] Registering platform 'homebridge-dyson-pure-cool.DysonPureCoolPlatform'
[5/29/2021, 1:51:24 PM] ---
[5/29/2021, 1:51:24 PM] Loaded plugin: homebridge-fritz-platform@5.1.1-beta.3
[5/29/2021, 1:51:27 PM] Registering platform 'homebridge-fritz-platform.FritzPlatform'
[5/29/2021, 1:51:32 PM] ---
[5/29/2021, 1:51:32 PM] Loading ... platforms...
[5/29/2021, 1:51:32 PM] [Config] Initializing config platform...
[5/29/2021, 1:51:32 PM] [Config] Running in Service Mode
[5/29/2021, 1:51:32 PM] [TurtleBridge] Initializing Hue platform...
[5/29/2021, 1:51:32 PM] [TurtleBridge] homebridge-hue v0.13.11, node v14.17.0, homebridge v1.3.4
[5/29/2021, 1:51:32 PM] [Fritz] Initializing FritzPlatform platform...
[5/29/2021, 1:51:36 PM] URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at new Fritzbox (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:38:25)
    at /homebridge/node_modules/homebridge-fritz-platform/src/platform.js:84:38
    at Array.map (<anonymous>)
    at new FritzPlatform (/homebridge/node_modules/homebridge-fritz-platform/src/platform.js:79:25)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
[5/29/2021, 1:51:36 PM] Got SIGTERM, shutting down Homebridge...
[5/29/2021, 1:51:37 PM] [TurtleBridge] TurtleBridge: Signify Netherlands B.V. BSB002 bridge v1945091050, api v1.44.0
[5/29/2021, 1:51:37 PM] [TurtleBridge] TurtleBridge: 1 accessories
[5/29/2021, 1:51:37 PM] [TurtleBridge] masked debug info dumped to /homebridge/homebridge-hue.json.gz
[5/29/2021, 1:51:37 PM] Initializing platform accessory 'TurtleBridge'...
[5/29/2021, 1:51:37 PM] [TurtleBridge] TurtleBridge: 2 services
[5/29/2021, 1:51:41 PM] [TurtleBridge] goodbye
[5/29/2021, 1:51:42 PM] [HB Supervisor] Homebridge Process Ended. Code: 143, Signal: null
[5/29/2021, 1:51:47 PM] [HB Supervisor] Restarting Homebridge...
[5/29/2021, 1:51:47 PM] [HB Supervisor] Starting Homebridge with extra flags: -I -P /homebridge/node_modules
[5/29/2021, 1:51:47 PM] [HB Supervisor] Started Homebridge v1.3.4 with PID: 656
Initializing HAP-NodeJS v0.9.4...
[5/29/2021, 1:51:49 PM] Loaded config.json with 1 accessories and 4 platforms.
[5/29/2021, 1:51:50 PM] Loaded 17 cached accessories from cachedAccessories.
[5/29/2021, 1:51:50 PM] ---

**Comment by SeydX** [comment]
@CSchmidtDD 

it seems that your password contains special characters.

Could you change your password slightly and post it here? I need to see what characters are causing this so I can reproduce it.

**Comment by CSchmidtDD** [comment]
Hi @SeydX 

The Password is simiar to (with these exact special chars):
6x9%D^Ms5sCa9tHheN

**Comment by SeydX** [comment]
@CSchmidtDD 

should be fixed with the latest beta, can u test  it pls

**Comment by CSchmidtDD** [comment]
@SeydX 
Problem is fixed, thank yo uvery much.

I also removed the added port in the config.json, tested it successfully and it keeps working, FYI :)

**Comment by CSchmidtDD** [comment]
Hi @SeydX 
Unfortunately, the problem resurfaced after the update to 6.* and I can not seem to get get a grasp on what to blame it.

Config & stuff unchanged, only version updates so far. Any idea what might cause the exact same case after your extensive rework which I find quite remarkable.

Regards

**Comment by SeydX** [comment]
Can u post the log pls and maybe restarr fritzbox

**Comment by CSchmidtDD** [comment]
Current setup:
- FB 7590 v7.27
- HB with Plug-in v6.0.8

Restarted both to no avail. Lights nothing to declare, really no messages from the plug-in so far.

Enabled Debug-Log (other Log Boxes were already enabled), restarted and checked. 

Behaviour persists, switching is done via HomeBridge, but does not execute it in reality. The Switch-State does not seem to be displayed correctly now as well. (It is not reverting to its real state after a "switch" and just stays toggled off, even if it is really still turned on).

Hope that helps and thanks for the fast reply!

**Comment by SeydX** [comment]
Can u post your current config.json pls 

v6 changed a bit

**Comment by SeydX** [comment]
And please check your config with the example config

https://github.com/SeydX/homebridge-fritz-platform/blob/master/example/example-config.json

(You need to set ``"active": true``)

**Comment by CSchmidtDD** [comment]
Hi @SeydX

The problem does seem related to [Issue-204](https://github.com/SeydX/homebridge-fritz-platform/issues/204), but whenever I set active: true in the device it will throw an error and crash the homebridge. 

When commenting out "active": true, in the device for fritzbox, it will work as described above - doesn't do anything.

Here the logmessage that kills homebridge, when setting device to active:
```[6/28/2021, 12:03:07 PM] URIError: URI malformed
    at decodeURIComponent (<anonymous>)
    at new Fritzbox (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:40:25)
    at /homebridge/node_modules/homebridge-fritz-platform/src/accessories/router/router.setup.js:29:27
    at Array.forEach (<anonymous>)
    at Setup (/homebridge/node_modules/homebridge-fritz-platform/src/accessories/router/router.setup.js:9:16)
    at new FritzPlatform (/homebridge/node_modules/homebridge-fritz-platform/src/platform.js:82:5)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
[6/28/2021, 12:03:07 PM] Got SIGTERM, shutting down Homebridge...```

**Comment by SeydX** [comment]
> Hi @SeydX
> 
> I added active:true everywhere it did not stand yet - (e.g. smarthome actors) - but that did not do the trick.
> 
> The problem does seem related to [Issue-204](https://github.com/SeydX/homebridge-fritz-platform/issues/204), but whenever I set active: true in the device for the fritzbox itself it will throw an error and crash the homebridge.
> 
> When commenting out "active": true, in the device for fritzbox, it will work as described above - doesn't do anything.
> 
> Here the logmessage that kills homebridge, when setting device to active:
> 
> ```
> [6/28/2021, 12:03:07 PM] URIError: URI malformed
>     at decodeURIComponent (<anonymous>)
>     at new Fritzbox (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:40:25)
>     at /homebridge/node_modules/homebridge-fritz-platform/src/accessories/router/router.setup.js:29:27
>     at Array.forEach (<anonymous>)
>     at Setup (/homebridge/node_modules/homebridge-fritz-platform/src/accessories/router/router.setup.js:9:16)
>     at new FritzPlatform (/homebridge/node_modules/homebridge-fritz-platform/src/platform.js:82:5)
>     at /usr/local/lib/node_modules/homebridge/src/server.ts:440:40
>     at Array.forEach (<anonymous>)
>     at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
>     at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
> [6/28/2021, 12:03:07 PM] Got SIGTERM, shutting down Homebridge...
> ```

Can u change your password for the fritzbox

**Comment by CSchmidtDD** [comment]
Changed to an easier password with aaaabbbeeee123! and it suddenly worked (with active true on the device).

So I guess the password problem is back, can confirm this.

**Comment by SeydX** [comment]
v6.0.10 should fix it again, can u confirm pls

**Comment by CSchmidtDD** [comment]
v6.0.10 fixed it, thanks a bunch :)
