### ISSUE TITLE
Some error Massage with 5.1.1

### ISSUE THREAD

**Issue by Christian-CFP** [SeydX/homebridge-fritz-platform#186]
FB 7.27

[30.05.21, 07:40] [FritzPlatform] Fritz!Box 7590: An error occured during getting state (dect)

[30.05.21, 07:40] [FritzPlatform] Error: Action "X_AVM-DE_CreateUrlSID" of "urn:dslforum-org:service:DeviceInfo:1" not known!
    at Service.execAction (/home/hoobs/.hoobs/node_modules/@seydx/fritzbox/lib/service.js:116:13)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)

**Comment by SeydX** [comment]
Fixed in v5.1.2
