### ISSUE TITLE
Connection error with FRITZ!WLAN Repeater 1750E

### ISSUE THREAD

**Issue by Terbiii** [SeydX/homebridge-fritz-platform#200]
**Describe the bug**
I updated the plugin for Homebridge to the newest Version. Now running v6.0.5
After the update vom v5 to v6 I got connection error to my FritzRepeater and I didn't get the status information

I tried different changes in the config
- change the password to not include special characters 
- "ssl" true / flase
- "oldFW" true / false
- "tr064" true / false
- include a empty "username" as a Repeater has no username

last config was
```
{
    "active": true,
    "name": "Repeater",
    "host": "192.168.1.2",
    "username": "",
    "password": "xxx",
    "ssl": true,
    "tr064": true,
    "igd": false,
    "manufacturer": "AVM",
    "model": "FRITZ!WLAN Repeater 1750E",
    "oldFW": false,
    "wifiUnits": 2,
    "connection": "repeater",
    "options": {
        "wifi_2ghz": "switch",
        "wifi_5ghz": "switch",
        "wifi_guest": "switch"
    }
}
```

**Error message**
```
[6/23/2021, 8:13:46 PM] [FritzPlatform] Repeater Wifi guest (wifi_guest): An error occured during getting state!
[6/23/2021, 8:13:46 PM] [FritzPlatform] Error: Unauthorized
    at Object.exports.request (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:213:20)
    at Service.execAction (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Handler.get (/homebridge/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:241:28)
    at Handler.poll (/homebridge/node_modules/homebridge-fritz-platform/src/accessories/extras/extras.handler.js:774:13) {
  title: 'Invalid Response',
  code: 401,
  url: 'https://false:passwordxxx@192.168.1.2:49443/upnp/control/wlanconfig3'
}
```

**Comment by SeydX** [comment]
Try adding a username ("admin") to the config

**Comment by Terbiii** [comment]
thanks for the quick response, worked with "admin" as username👍🏼
