### ISSUE TITLE
Error message every 15  seconds

### ISSUE THREAD

**Issue by Flieger37** [SeydX/homebridge-fritz-platform#202]
Hi,

i am getting the following error messages every 15 seconds. Version is 6.05.

[26/06/2021, 11:52:14] [FritzPlatform] Error: Internal Server Error
    at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:213:20)
    at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/presence/presence.handler.js:257:26) {
  title: 'Invalid Response',
  code: 500,
  url: 'https://homebridge:password@x.x.x.x:49443/upnp/control/hosts'
}

Any ideas?

Regards
Martin

**Comment by SeydX** [comment]
Which FritzBox and FW?

**Comment by Flieger37** [comment]
It's a 7590 with FRITZ!OS 07.27

**Comment by SeydX** [comment]
Can u try v6.0.6 pls - Added some more error information which would help to fix the issue

**Comment by Flieger37** [comment]
After updating to v6.0.6 and rebooting, the error look like this every 15 seconds:

[27/06/2021, 08:49:56] [homebridge-fritz-platform] This plugin slows down Homebridge. The read handler for the characteristic 'Download' was slow to respond! See https://git.io/JtMGR for more info.
[27/06/2021, 08:49:56] [FritzPlatform] An error occurred during polling hosts!
[27/06/2021, 08:49:57] [FritzPlatform] Error: Internal Server Error
    at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:227:20)
    at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/presence/presence.handler.js:257:26) {
  title: 'Invalid Response',
  code: 500,
  soap: { errorCode: '714', errorDescription: 'NoSuchEntryInArray' },
  url: 'https://homebridge:password@x.x.x.x:49443/upnp/control/hosts'
}

**Comment by SeydX** [comment]
> After updating to v6.0.6 and rebooting, the error look like this every 15 seconds:
> 
> [27/06/2021, 08:49:56] [homebridge-fritz-platform] This plugin slows down Homebridge. The read handler for the characteristic 'Download' was slow to respond! See https://git.io/JtMGR for more info.
> [27/06/2021, 08:49:56] [FritzPlatform] An error occurred during polling hosts!
> [27/06/2021, 08:49:57] [FritzPlatform] Error: Internal Server Error
> at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
> at processTicksAndRejections (internal/process/task_queues.js:95:5)
> at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:227:20)
> at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
> at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/presence/presence.handler.js:257:26) {
> title: 'Invalid Response',
> code: 500,
> soap: { errorCode: '714', errorDescription: 'NoSuchEntryInArray' },
> url: 'https://homebridge:password@x.x.x.x:49443/upnp/control/hosts'
> }

The error means it can not find the given ip address for the presence user. Can you put the MAC address in the config for all presence user instead of the ip address pls and then restart hb

**Comment by Flieger37** [comment]
There is a new option "Private Relay" that hides the IP address of the device in iOS 15. It was actually activated. I have switched Private-Relay off, switched WLAN off/on, rebooted HB. But same result.

The 7590 shows the same MAC address and the same IP address for the iPhone as before in the active devices list - so obviously there is no difference for the 7590. And as you just check the status in the 7590 and don't interact with the iPhone, there was only a little chance, that Private-Relay on/off would change anything ... but I wanted to give it a try ;-)

HB protocol after switching Private-Relay off in the iPhone and changing IP address against MAC address:
================================================================================
[27/06/2021, 10:07:58] [FritzPlatform] Error: Internal Server Error
    at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:227:20)
    at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/presence/presence.handler.js:257:26) {
  title: 'Invalid Response',
  code: 500,
  soap: { errorCode: '714', errorDescription: 'NoSuchEntryInArray' },
  url: 'https://homebridge:password@x.x.x.x:49443/upnp/control/hosts'
}

**Comment by SeydX** [comment]
Published a new Beta version, can u try it pls?

``sudo npm i -g homebridge-fritz-platform@beta``

You can always switch back to/from Beta from/to official without loosing any data

**Comment by Flieger37** [comment]
I just have deleted the complete "presence" part from the config. Checked if the devices are deleted from cache also and newly entered the devices one by one - always rebooting HB after every presence-device.

B.t.w. deleting the entry by pressing "x" in the upper right corner of the UI did not delete the presence entry - I had to go directly into the config to delete the presence-devices.

The error then occurred when I entered a device that is not in the "Active Connections" list and not in the "Inactive Connections" list of the Fritz!Box (and it was not the Beta iOS iPhone).

The device must have been dropped out of the 7590s inactive list after cleaning it up a few days ago.

As the device is online just every 3-4 months - sporadic visits of our son ;-) - it would be great if you could change the error handling and the device could also be shown as "not present" if it's not in the active and not in the inactive list of the 7590, because when it is seen again in our WLAN after a couple of months, it will have the same MAC address again and it will be the same person.

**Comment by SeydX** [comment]
Thx for the info, published a new beta version (6.0.7-beta.1) which should fix it. Can u try it pls?

``sudo npm i -g homebridge-fritz-platform@beta``

**Comment by Flieger37** [comment]
Great! It's working - added the user with a MAC address that is not in the active or inactive list of the 7590 and the presence device shows "not present". Thank you for extremely fast solving & fixing. 

All other devices are running without problems: 1*7590, 1*7580, 2*AVM3000, 4*1750E, 3*546E, 1*DECT100 and some DECT200 and DECT310, Telegram, Callmonmitor.... - it's really a mighty plugin and I very much appreciate your work!

**Comment by SeydX** [comment]
Great :)

**Comment by SeydX** [comment]
v6.0.7 is online now
