### ISSUE TITLE
can't get state of Fritzbox 

### ISSUE THREAD

**Issue by timchje** [SeydX/homebridge-fritz-platform#209]
`[01/07/2021, 14:22:21] [FritzPlatform] FritzBox (dsl): An error occured during getting state!
[01/07/2021, 14:22:21] [FritzPlatform] Error: Internal Server Error
    at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:227:20)
    at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Handler.get (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:101:28)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:967:11) {
  title: 'Invalid Response',
  code: 500,
  soap: { errorCode: '401', errorDescription: 'Invalid Action' },
  url: 'https://homebridge:*********@192.168.1.1:49443/upnp/control/wanpppconn1'
}`

I guys i cant get the FB Switch to work. Getting the Errore above. Prescence sensors and Guest Wifi switch working great - im just not getting the state of the Fritzbox it self 

gerne auch in Deutsch :) 

greez Tim

**Comment by eibi63** [comment]
Gleiches oder ähnlichen Problem bei mir
[04/07/2021, 10:38:53] [FritzPlatform] Fritz!Box Wifi guest (wifi_guest): An error occured during getting state!
[04/07/2021, 10:38:53] [FritzPlatform] Error: connect EHOSTUNREACH 192.168.178.1:49443
    at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:102:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:227:20)
    at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Handler.get (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:241:28)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/extras/extras.handler.js:766:13) {
  title: 'No Response',
  code: 'EHOSTUNREACH',
  soap: {},
  url: 'https://XXXXX:XXXXX@192.168.178.1:49443/upnp/control/wlanconfig3'
}
[04/07/2021, 10:38:53] [FritzPlatform] An error occurred during polling smarthome devices!
[04/07/2021, 10:38:53] [FritzPlatform] Error: connect EHOSTUNREACH 192.168.178.1:49443
    at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:102:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:227:20)
    at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Fritzbox.getSmarthomeDevices (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:215:22)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/smarthome/smarthome.handler.js:1663:28) {
  title: 'No Response',
  code: 'EHOSTUNREACH',
  soap: {},
  url: 'https://XXXXX:XXXXX@192.168.178.1:49443/upnp/control/deviceconfig'
}

**Comment by SeydX** [comment]
> Gleiches oder ähnlichen Problem bei mir
> [04/07/2021, 10:38:53] [FritzPlatform] Fritz!Box Wifi guest (wifi_guest): An error occured during getting state!
> [04/07/2021, 10:38:53] [FritzPlatform] Error: connect EHOSTUNREACH 192.168.178.1:49443
> at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:102:21)
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:95:5)
> at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:227:20)
> at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
> at Handler.get (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:241:28)
> at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/extras/extras.handler.js:766:13) {
> title: 'No Response',
> code: 'EHOSTUNREACH',
> soap: {},
> url: 'https://XXXXX:XXXXX@192.168.178.1:49443/upnp/control/wlanconfig3'
> }
> [04/07/2021, 10:38:53] [FritzPlatform] An error occurred during polling smarthome devices!
> [04/07/2021, 10:38:53] [FritzPlatform] Error: connect EHOSTUNREACH 192.168.178.1:49443
> at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:102:21)
> at runMicrotasks ()
> at processTicksAndRejections (internal/process/task_queues.js:95:5)
> at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:227:20)
> at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
> at Fritzbox.getSmarthomeDevices (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:215:22)
> at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/smarthome/smarthome.handler.js:1663:28) {
> title: 'No Response',
> code: 'EHOSTUNREACH',
> soap: {},
> url: 'https://XXXXX:XXXXX@192.168.178.1:49443/upnp/control/deviceconfig'
> }

Your Fritzbox ist not reachable 

`EHOSTUNREACH`

**Comment by SeydX** [comment]
> `[01/07/2021, 14:22:21] [FritzPlatform] FritzBox (dsl): An error occured during getting state! [01/07/2021, 14:22:21] [FritzPlatform] Error: Internal Server Error at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:95:5) at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:227:20) at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20) at Handler.get (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:101:28) at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:967:11) { title: 'Invalid Response', code: 500, soap: { errorCode: '401', errorDescription: 'Invalid Action' }, url: 'https://homebridge:*********@192.168.1.1:49443/upnp/control/wanpppconn1' }`
> 
> I guys i cant get the FB Switch to work. Getting the Errore above. Prescence sensors and Guest Wifi switch working great - im just not getting the state of the Fritzbox it self
> 
> gerne auch in Deutsch :)
> 
> greez Tim

Fritzbox Model ?

**Comment by timchje** [comment]
7590

**Comment by SeydX** [comment]
`{ errorCode: '401', errorDescription: 'Invalid Action' }`

Deutet auf einen User ohne richtige/volle Berechtigungen. Evtl mal checken bzw neuen User anlegen mit allen Berechtigungen, anschließend in HB den neuen user eintragenund nochmal probieren

**Comment by eibi63** [comment]
Das habe ich auch gemacht. Jetzt läuft es.

**Comment by Triopal** [comment]
[09/08/2021, 20:41:29] [FritzPlatform] FritzBox (dsl): An error occured during getting state!
[09/08/2021, 20:41:29] [FritzPlatform] Error: Internal Server Error
    at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:227:20)
    at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Handler.get (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:101:28)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:967:11) {
  title: 'Invalid Response',
  code: 500,
  soap: { errorCode: '401', errorDescription: 'Invalid Action' },
  url: 'https://Homebridge:****@192.168.178.1:49443/upnp/control/wanpppconn1'
}

**Guten Abend,
diese Fehlermeldung erhalte ich leider in der HB alle paar Sekunden. Einen neuen Benutzer habe ich in der FritzBox (7490 OS 07.27) mit allen Rechten bereits erstellt, leider ohne Abhilfe. Leider ist mein Latein damit am Ende. Die Steuerung der Smarthomeprodukte funktioniert tadellos. Aber ignorieren fällt doch schwer.**

Die zugehörige Konfiguration:
],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "FritzPlatform",
            "debug": false,
            "warn": true,
            "error": true,
            "extendedError": true,
            "devices": [
                {
                    "active": true,
                    "name": "FritzBox",
                    "host": "192.168.178.1",
                    "username": "Homebridge",
                    "password": "****",
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "model": "7490",
                    "wifiUnits": 2,
                    "master": true,
                    "connection": "dsl",
                    "options": {
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "switch"
                    }
                },
                {
                    "active": false,
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
                    "wifiUnits": 2
                }
            ],
            "smarthome": [
                {
                    "active": true,
                    "name": "Heizung Schlafzimmer",
                    "ain": "119610827456",
                    "group": false,
                    "window": true,
                    "openWindow": false,
                    "battery": true,
                    "accTypeGroup": "thermostat",
                    "accType": "thermostat"
                },
                {
                    "active": true,
                    "name": "Heizung Badezimmer ",
                    "ain": "119600964264",
                    "externTemperatureSensor": false,
                    "window": true,
                    "battery": true,
                    "accType": "thermostat"
                },
                {
                    "active": true,
                    "name": "Heizung Arbeitszimmer",
                    "ain": "119590559496",
                    "window": true,
                    "openWindow": false,
                    "battery": true,
                    "accType": "thermostat"
                },
                {
                    "active": true,
                    "name": "Heizung Wohnzimmer Balkon",
                    "ain": "119590299152",
                    "group": false,
                    "window": true,
                    "openWindow": false,
                    "battery": true,
                    "accTypeGroup": "thermostat",
                    "accType": "thermostat"
                },
                {
                    "active": true,
                    "name": "Heizung Wohnzimmer Fenster",
                    "ain": "11959 0299336",
                    "window": true,
                    "openWindow": false,
                    "battery": true,
                    "accType": "thermostat"
                }
            ],
            "callmonitor": {
                "active": false
            },
            "options": {
                "polling": {
                    "timer": 15
                }
            },
            "platform": "FritzPlatform"
        }
