### ISSUE TITLE
homebridge-fritz-platform : syntax error after updating node.js to v14.17.5

### ISSUE THREAD

**Issue by maccaronics** [SeydX/homebridge-fritz-platform#223]
**Describe the bug**

**To Reproduce**
 - Restarting Homebridge throws error in the Log. All "Fritz"-Devices in Homekit are telling "no answer" (Keine Antwort)

**Expected behavior**
Just a working plugin again

**Screenshots**
[12/08/2021, 10:40:43] Registering platform 'homebridge-fritz-platform.FritzPlatform'
[12/08/2021, 10:40:43] [FritzPlatform] Loaded homebridge-fritz-platform v6.0.14 child bridge successfully
[12/08/2021, 10:40:43] Loaded 19 cached accessories from cachedAccessories.0E5CEC3C4A7D.
(node:9783) UnhandledPromiseRejectionWarning: /usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/googleapis/build/src/apis/dialogflow/v2beta1.js:2370
ge[310]:   address: '192.168.188.45',
       ^
SyntaxError: Unexpected token ':'
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/googleapis/build/src/apis/dialogflow/index.js:20:19)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9783) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9783) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Additional context**
I'm wondering why the IP Address 192.168.188.45 is shown here. I do not have any device "connected" with this IP address in the Fritz Plugin anymore. Previously is was the IP Adress of my AVR.

Thanks in advance for your support :-)

**Comment by maccaronics** [comment]
Reinstalling the plug in solved it. :-)
