### ISSUE TITLE
[FritzPlatform] TypeError: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by potatobrain1337** [SeydX/homebridge-fritz-platform#236]
- homebridge-fritz-platform v6.0.16
- running this in docker via raspberry pi
- below JSON contains configred bridge - just removed it here
- creates the following error:
```
[9/28/2021, 3:57:50 AM] [FritzPlatform] An error occurred during polling smarthome devices!
[9/28/2021, 3:57:50 AM] [FritzPlatform] TypeError: Cannot read property 'type' of undefined
    at /homebridge/node_modules/homebridge-fritz-platform/src/accessories/smarthome/smarthome.handler.js:1739:38
    at Array.filter (<anonymous>)
    at Handler.poll (/homebridge/node_modules/homebridge-fritz-platform/src/accessories/smarthome/smarthome.handler.js:1737:46)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

config
```
{
    "bridge": {
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "FritzPlatform",
            "warn": true,
            "error": true,
            "extendedError": true,
            "devices": [
                {
                    "active": true,
                    "name": "FRITZ!Box 7590",
                    "host": "192.168.178.1",
					"port": 49000,
                    "username": "XXX",
                    "password": "XXX",
					"manufacturer": "Fritz Box",
					"model": "7590",
					"serialNumber": "12345",
					"master": true,
                    "ssl": true,
                    "tr064": true,
                    "igd": false,
	            "readOnly": false,
                    "hide": true,
                    "connection": "dsl",
                    "wifiUnits": 2,
                    "options": {
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "switch",
                        "wifi_guest": "switch",
                        "wps": "characteristic",
                        "aw": "characteristic",
                        "deflection": "switch",
                        "led": "switch",
                        "lock": "switch",
                        "dect": "switch",
                        "reconnect": "switch",
                        "broadband": "characteristic"
                    }
                }
            ],
            "smarthome": [
                {
                    "active": true,
                    "name": "Schlafzimmer - TV / Audio",
                    "ain": "11630 0000001",
                    "energy": true,
                    "startValue": 1,
                    "temperature": true,
                    "accType": "switch"
                },
                {
                    "active": false,
                    "name": "FRITZ!DECT 200 #2 - Wohnzimmer (TV)",
                    "ain": "11630 0000002",
                    "energy": true,
                    "startValue": 1,
                    "temperature": true,
                    "accType": "switch"
                },
                {
                    "active": false,
                    "name": "FRITZ!DECT 200 #3 - Wohnzimmer (MAC)",
                    "ain": "11630 0000003",
                    "energy": true,
                    "startValue": 1,
                    "temperature": true,
                    "accType": "switch"
                },
                {
                    "active": false,
                    "name": "FRITZ!DECT 200 #7 - Wohnzimmer (PC)",
                    "ain": "11630 0000004",
                    "energy": true,
                    "startValue": 1,
                    "temperature": true,
                    "accType": "switch"
                },
                {
                    "active": false,
                    "name": "FRITZ!DECT 200 #8 - Wohnzimmer (Audio)",
                    "ain": "11630 0000005",
                    "energy": true,
                    "startValue": 1,
                    "temperature": true,
                    "accType": "switch"
                },
                {
                    "active": false,
                    "name": "FRITZ!DECT 301 #4 - Badezimmer",
                    "ain": "09995 0000001",
                    "temperature": true,
                    "window": true,
                    "openWindow": true,
                    "battery": true,
                    "accType": "thermostat"
                },
                {
                    "active": false,
                    "name": "FRITZ!DECT 301 #5 - Schlafzimmer",
                    "ain": "09995 0000003",
                    "temperature": true,
                    "window": true,
                    "openWindow": true,
                    "battery": true,
                    "accType": "thermostat"
                },
                {
                    "active": false,
                    "name": "FRITZ!DECT 301 #6 - Wohnzimmer",
                    "ain": "09995 0000003",
                    "temperature": true,
                    "window": true,
                    "openWindow": true,
                    "battery": true,
                    "accType": "thermostat"
                }
            ],
            "options": {
                "polling": {
                    "timer": 15,
                    "timerSmarthomeButtons": 5,
                    "exclude": []
                }
            },
            "platform": "FritzPlatform"
        },
        {
            "name": "Hue",
            "anyOn": true,
            "effects": true,
            "hosts": [
                "192.168.178.28"
            ],
            "lights": true,
            "nativeHomeKitLights": false,
            "nativeHomeKitSensors": false,
            "resource": true,
            "users": {
                "XXX": "XXX"
            },
            "platform": "Hue"
        }
    ]
}
```

**Comment by SeydX** [comment]
can u try v6.0.19-beta.0 pls

``sudo npm i -g homebridge-fritz-platform@beta``

**Comment by potatobrain1337** [comment]
> can u try v6.0.19-beta.0 pls
> 
> `sudo npm i -g homebridge-fritz-platform@beta`

works like a charm - thank you so much @SeydX - exception is gone ond i look at this now 🥇 

![image](https://user-images.githubusercontent.com/91511422/136122085-836b895a-cdf1-4da3-89e9-7f7829c9b6f6.png)

**Comment by SeydX** [comment]
Nice, will push it to 6.0.19

**Comment by SeydX** [comment]
v6.0.19 online

**Comment by Seeeebi-sudo** [comment]
Hi,

im getting the same error with FB 6591 over internet and 3 FDect 301 devices... They are showing up, but the sensors are greyed out. The log shows 

`[16/12/2022, 20:12:34] [FritzPlatform] TypeError: Cannot read properties of undefined (reading '$')
    at /var/lib/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:235:83
    at Array.filter (<anonymous>)
    at Fritzbox.getSmarthomeDevices (/var/lib/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:235:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Handler.poll (/var/lib/homebridge/node_modules/homebridge-fritz-platform/src/accessories/smarthome/smarthome.handler.js:1755:28)`

I am on V 6.0.19 on a homebridge server on Raspberry Pi...

DO you need any other information?

Thanks! @seydx
