### ISSUE TITLE
An error occured during getting state!

### ISSUE THREAD

**Issue by CM-UH** [SeydX/homebridge-fritz-platform#242]
I found in the Homebridge Log this messages:

> [11/10/2021, 20:25:31] [FritzPlatform] Fritzbox7590 Led (led): An error occured during getting state!
[11/10/2021, 20:25:31] [FritzPlatform] Error: Unauthorized
    at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:230:20)
    at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Handler.get (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:350:28)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/extras/extras.handler.js:783:13) {
  title: 'Invalid Response',
  code: 401,
  soap: {},
  url: 'https://Homebridge:xxxxxx@192.168.2.2:49443/upnp/control/deviceconfig'
}

The strange thing everything seems to work no problems for me.
Homebridge v1.3.5 Plugin version 6.0.19

**Comment by SeydX** [comment]
```
[11/10/2021, 20:25:31] [FritzPlatform] Error: Unauthorized
```

The plugin can no longer log in to the FritzBox. Have you tried to restart the FritzBox?

**Comment by Kienz** [comment]
Doesn’t help. I can change the state from Home app (eg. Voice mail on/off). But sometimes it just works after some tries. With homebridge version 1.3.4 it works.

**Comment by Kienz** [comment]
I also tested another user (the main user) and recreated the user for homebridge. On the WebUI I can successfully login with both users. But in homebridge the error is shown.

**Comment by CM-UH** [comment]
Some new ideas???
Everything is up to date but still a lot of debug messages.
But the funktion is ok.

**Comment by misanthrophy** [comment]
same issue for me on a fresh install.

doesn't matter if I backup/restore from another homebridge, add the plugin and settings manually or creating a new user, still the same.

On my main homebridge, running for years it is still working, even after a reboot, so only new installations are affected.

**Comment by Kienz** [comment]
Disable "SSL" in the homebridge-fritz-platform config solved it for me. @seydx But why?
See https://github.com/seydx/homebridge-fritz-platform/issues/254
