### ISSUE TITLE
Error getting any status - Probably because my FritzBox has no username?

### ISSUE THREAD

**Issue by Ms-Sudo** [SeydX/homebridge-fritz-platform#244]
I am getting all kinds of errors and cannot control anything from my FritzBox.

I am assuming that the same would happen if the password is wrong. My FritzBox only requests a password, but no username. So I left the username field empty in the plugin (credentials).

Fritz (aw): An error occured during getting state!
[18.10.2021, 15:42:17] [Fritz] Error: Unauthorized
    at Object.exports.request (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:230:20)
    at Service.execAction (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Handler.get (/usr/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:306:28)
    at Handler.poll (/usr/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:1000:19) {
  title: 'Invalid Response',
  code: 401,
  soap: {},

**To Reproduce**
Devices -> Credentials
Leave Username blank or use wrong password.

**Additional context**
I am using the correct password and IP address. 

I also tried to add 
_"username": "",_
to the configuration but get the same error.

Any help is appreciated.

Thanks!

**Comment by Ms-Sudo** [comment]
Thank you. I updated my FritzBox and then it worked.
