### ISSUE TITLE
Fritz plugin Fehler

### ISSUE THREAD

**Issue by marcelfranzmann** [seydx/homebridge-fritz-platform#249]
Ich bekomme das plugin nicht ins laufen. Ich bekomme immer wieder den selben fehler:

FRITZ!BOX 7590 Wifi 2ghz (wifi_2ghz): An error occured during getting state!
[10/11/2021, 22:19:47] [FritzPlatform] Error: Internal Server Error
    at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:230:20)
    at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Handler.get (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:186:28)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/extras/extras.handler.js:783:13) {
  title: 'Invalid Response',
  code: 500,
  soap: {
    errorCode: '401',
    errorDescription: '',
    action: 'urn:dslforum-org:service:WLANConfiguration:1#GetInfo'

**Comment by seydx** [comment]
`errorCode: '401',`

Bedeutet unauthoriziert. Evtl mal die Box neustarten? Recht kontrollieren?

lg
