### ISSUE TITLE
Connection Error  Fritz OS 7.29 unauthorized

### ISSUE THREAD

**Issue by Kragothius** [seydx/homebridge-fritz-platform#254]
**Describe the bug**
Added New Device Fritz!Box 7530 with Fritz!OS 07.29

**To Reproduce**
1. Add Device, Enter Credentials with Configured User Name and Password based on Fritz User.
2. Save
3. Restart Homebridge
4. See error in Log

[FritzPlatform] Fritz7530 (dsl): An error occured during getting state!
[FritzPlatform] Error: Unauthorized
at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:230:20)
    at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Handler.get (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:101:28)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:979:11) {
  title: 'Invalid Response',
  code: 401,
  soap: {},
  url: 'https://username:password@FritzboxIP:49443/upnp/control/wanpppconn1'
}

5. I already checked the Network and User Configuration for TR064 Access > OK (other Apps can also Connect)
6. Checked https://FritzboxIP:49443/upnp/control/wanpppconn1 > getting 404 Not Found > might be the Problem?
7. Homebridge restarting loop

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser safari
 - Version 15.1

**Smartphone (please complete the following information):**
 - Device: Iphone 12
 - OS: IOS 15.1.1
 - Browser safari
 - Version 15.1

**Comment by Kragothius** [comment]
Turned off SSL for Testing > Problem is gone

Any Ideas would help me.

Gruß

**Comment by CM-UH** [comment]
How and where did you switch off SSL????

Schönen Gruß
Udo

**Comment by Kragothius** [comment]
> How and where did you switch off SSL????
> 
> Schönen Gruß Udo

I turned off SSL in the Homebridge Fritz Platform Plugin > Device > Advanced > SSL

"devices": [
                {
                    "active": true,
                    "name": "Fritz7530",
                    "host": "HOSTIP",
                    "username": "user",
                    "password": "password",
                    "ssl": false, <<<<<<<<<<<<<<<<<<<<<
                    "tr064": true,
                    "igd": false,
                    "wifiUnits": 2,
                    "master": true,
                    "connection": "dsl",
                    "options": {
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "switch",
                        "wifi_guest": "switch",
                        "aw": "characteristic"
                    }
                }

**Comment by CM-UH** [comment]
Great!!
ssl = false  -> works for me!!

Thanks a lot

**Comment by dis0rdr** [comment]
Same issue on Fritz!Box 7590 with 7.29. Disabling SSL changes nothing for me. Tried every option without success. 

  title: 'Invalid Response',
  code: 500,
  soap: {
    errorCode: '401',
    errorDescription: 'Invalid Action',
    action: 'urn:dslforum-org:service:WANPPPConnection:1#GetInfo'
  },
  url: 'http://fritzXXX:pw@1.2.3.4:49000/upnp/control/wanpppconn1'
}

**Comment by flok** [comment]
> Same issue on Fritz!Box 7590 with 7.29. Disabling SSL changes nothing for me. Tried every option without success.
> 
> title: 'Invalid Response', code: 500, soap: { errorCode: '401', errorDescription: 'Invalid Action', action: 'urn:dslforum-org:service:WANPPPConnection:1#GetInfo' }, url: 'http://fritzXXX:pw@1.2.3.4:49000/upnp/control/wanpppconn1' }

if you  deactivate SSL the port changes from 49000 to 49443. make the changes inside your config and you will get a connection

**Comment by steffann** [comment]
I have tested this with both 7.28 and 7.29, both give the same error:

```
[27/12/2021, 17:58:51] [FritzPlatform] Error: Internal Server Error
    at Object.exports.request (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at exports.requestXml (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:230:20)
    at Service.execAction (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Handler.get (/usr/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:101:28)
    at Handler.poll (/usr/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:979:11) {
  title: 'Invalid Response',
  code: 500,
  soap: {
    errorCode: '401',
    errorDescription: 'Invalid Action',
    action: 'urn:dslforum-org:service:WANPPPConnection:1#GetInfo'
  },
  url: 'http://homebridge:xxxxxx@192.168.178.1:49000/upnp/control/wanpppconn1'
}
```

Potentially relevant versions:
- homebridge@1.3.8
- homebridge-config-ui-x@4.41.5
- homebridge-fritz-platform@6.0.19

**Comment by xazac** [comment]
Same error here with FritzBox 7590AX running FritzOS 7.29

**Comment by dis0rdr** [comment]
For me I could fix it by changing from „DSL“ or „Cable“ mode to „repeater“. Hope this helps.

**Comment by flok** [comment]
> For me I could fix it by changing from „DSL“ or „Cable“ mode to „repeater“. Hope this helps.

tried that but still getting error on `/upnp/control/wlanconfig1`

**Comment by zilluss** [comment]
Same issue here, neither changing the SSL nor the connection option fixed the errors.

**Comment by mrxoom1274** [comment]
Same problem. FritzOS 7.29
HOMEBRIDGE 1.4.0
ON QNAP Docker

![image](https://user-images.githubusercontent.com/70346648/152020623-10781831-beed-4e37-b085-41badb639466.jpeg)

**Comment by jvacek** [comment]
Bump

**Comment by hawk2004** [comment]
does everyone have a solution or some news for the problem?
[21/08/2022, 12:17:38] [FritzPlatform] An error occurred during polling hosts!
[21/08/2022, 12:17:38] [FritzPlatform] Error: Internal Server Error
    at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at runMicrotasks (<anonymous>)
