### ISSUE TITLE
Hostadresse *.myfritz.net oder VPN statt lokaler IP Adresse

### ISSUE THREAD

**Issue by A6neu** [seydx/homebridge-fritz-platform#259]
Hallo Zusammen,

ist es möglich statt einer lokalen IP Adresse eine *.myfritz.net Account Adresse oder beispielsweise eine VPN Adresse zu verwenden?

Ich bin schon Stunden am probieren, bekomme es aber leider nicht hin. Hintergrund meine Fritz!Box wurde zum ausschließlichen Modem + Telefonanlage mit vier schaltbaren DECT Steckdosen degradiert. Die FritzBox ist aus meinem Hauptnetzwerk nicht zu erreichen. Gerne würde ich meine vorhandenen Fritz!Dect200 Steckdosen mit Siri Befehlen steuern/schalten und dazu die Homebridge Plattform sowie das Homebridge-fritz-platform Tool nutzen.

Wie geschrieben komme ich aus meinem Haupt LAN nicht auf die Fritz!Box und brauche daher einen Zugang via VPN oder Fritz Account. Mit der Suchfunktion hab ich leider nichts finden können.

Ich hab mein myfritz Zugang als Host eingetragen, laufe dann allerdings leider auf folgenden Fehler:

Error: connect ETIMEDOUT xxx.xxx.xxx.xxx:49000 bzw. 47128 (geht auch nicht)
 at Object.exports.request (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:103:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at exports.requestXml (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:230:20)
    at Fritzbox.parseDesc (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:96:20)
    at Fritzbox.initialize (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:54:7)
    at Fritzbox.getSmarthomeDevices (/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/fritzbox.js:220:5)
    at Handler.poll (/homebridge/node_modules/homebridge-fritz-platform/src/accessories/smarthome/smarthome.handler.js:1755:28) {
  title: 'No Response',
  code: 'ETIMEDOUT',
  soap: { action: 'unknown' },
  url: 'http://xxxxxxxxx.myfritz.net:49000/tr64desc.xml'
} 

bei Url ist allerdings eine http: statt eine http**s** Adresse hinterlegt.

Wäre super, wenn mir jemand weiterhelfen könnte, ich bin leider etwas unerfahren.

Viele Grüße
Mike

**Comment by crbyxwpzfl** [comment]
I have the same problem.
I think I figured out the correct url scheme `https://EXTERNALIP:PORT/tr064/tr64desc.xml`<br>
you can thest this url with any browser.
But I cant set this url with the additional `.../tr064/` because the plugin just replaces this.
I woud love to get this to work without the need to resetup my network setup.

to get the external ip of your fritzbox go to Internet>Freigaben>FritzBox-Dienste
[link](https://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/AVM_TR-064_remote.pdf)
