### ISSUE TITLE
url: 'https://XXX/.../upnp/control/wanipconnection1' -> Error 401

### ISSUE THREAD

**Issue by pennynet** [seydx/homebridge-fritz-platform#267]
Homebridge is logging permanently:
(FritzBox 7490, FritzOS 07.29; homebridge-config-ui-x@4.42.0; homebridge-fritz-platform@6.0.19) 

**************
[23/01/2022, 16:25:37] [FritzPlatform] FritzBox (cable): An error occured during getting state! 
[23/01/2022, 16:25:37] [FritzPlatform] Error: Internal Server Error
at Object.exports.request (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21) at runMicrotasks (<anonymous>)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at exports.requestXml (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:230:20)
at Service.execAction (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
at Handler.get (/usr/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:133:28)
at Handler.poll (/usr/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:979:11) { title: 'Invalid Response',
code: 500,
soap: {
errorCode: '401',
errorDescription: 'Invalid Action',
action: 'urn:dslforum-org:service:WANIPConnection:1#GetInfo'
},
url: 'https://admin:XXXXX@192.168.XXX.XXX:49443/upnp/control/wanipconnection1' }
**************

(same without SSL ->192.168.XXX.XXX:49000)

Does this matter or can it be ignored?

**Comment by temp** [comment]
Same problem here - can't tell if this is new, or if this has always been the case

**Comment by metalmini** [comment]
I am having the same issue, i do run a different fritzOS (FRITZ!OS:7.57) and running a different modem (FRITZ!Box 7530)

```[04/02/2024, 12:49:34] [FritzPlatform] Error: Internal Server Error
    at Object.exports.request (/var/lib/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at exports.requestXml (/var/lib/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:230:20)
    at Service.execAction (/var/lib/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Handler.get (/var/lib/homebridge/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:101:28)
    at Handler.poll (/var/lib/homebridge/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:979:11) {
  title: 'Invalid Response',
  code: 500,
  soap: {
    errorCode: '401',
    errorDescription: 'Invalid Action',
    action: 'urn:dslforum-org:service:WANPPPConnection:1#GetInfo'
  },
  url: 'https://user:pass@192.168.178.1:49443/upnp/control/wanpppconn1'
}
```

Whats going on here? Did i not configure the router correctly or is fritzOS being a pain in the butt?

If i try to retrieve the url stated in the logs i get a 404 (and some issues with the ssl cert not being safe).

**Comment by metalmini** [comment]
Ok, i think i figured it out. I have fiber, and i had DSL as a connectiontype. If i change that to Cable it seems to work and the error is gone.
