### ISSUE TITLE
led switch Fritz!Repeater 2400 on 07.39-95784

### ISSUE THREAD

**Issue by LutzRFrank** [seydx/homebridge-fritz-platform#287]
**Describe the bug**
I've added a Fritz!Repeater 2400 and can't switch LED on/off

the 2400 runs the latest Lab-Version 07.39-95784

**To Reproduce**
always

**Additional context**
Part of the Homebridge Log

[23.4.2022, 12:26:43] [FritzPlatform] [DEBUG] FRITZ-Powerline-1260E-DG Led (led): {"pid":"led","hide":{"ssoSet":true,"liveTv":true},"time":[],"data":{"ledSettings":{"canDim":"0","hasEnv":"0","ledDisplay":"0"}},"sid":"8d16b70a7cc9c892"}
[23.4.2022, 12:26:43] [FritzPlatform] [DEBUG] FRITZ-Powerline-1260E-GALLERY Led (led): GET CMD: {"xhr":"1","xhrId":"all","sid":"a6718d568dad385a","page":"led"}
[23.4.2022, 12:26:44] [FritzPlatform] [DEBUG] FRITZ-Powerline-1260E-GALLERY Led (led): {"pid":"led","hide":{"ssoSet":true,"liveTv":true},"time":[],"data":{"ledSettings":{"canDim":"0","hasEnv":"0","ledDisplay":"0"}},"sid":"a6718d568dad385a"}
[23.4.2022, 12:26:48] [FritzPlatform] [DEBUG] Fritz!DECT Repeater 100 (smarthome-temperature): {"name":"FRITZ!DECT Repeater 100","id":"16","ain":"116570446375","online":1,"bitmask":"1280","busy":0,"battery":false,"alert":false,"temperature":{"value":26.5,"offset":0},"humidity":false,"powermeter":false,"switch":false,"button":false,"blind":false,"thermostat":false,"light":false}
[23.4.2022, 12:26:54] [FritzPlatform] [DEBUG] Fritz!Box 6660 Cable Led (led): GET CMD: {"xhr":"1","xhrId":"all","sid":"bd99a0adaf28bc6a","page":"led"}
[23.4.2022, 12:26:54] [FritzPlatform] [DEBUG] Fritz!Box 6660 Cable Led (led): {"pid":"led","hide":{"docOpt":true,"docInfo":true,"rrd":true,"mobile":true,"ssoSet":true,"docLog":true,"liveTv":true,"boxExchange":true,"docStat":true,"docOv":true},"timeTillLogout":"1200","time":[],"data":{"ledSettings":{"canDim":"0","hasEnv":"0","ledDisplay":"0"}},"sid":"bd99a0adaf28bc6a"}
**[23.4.2022, 12:26:58] [FritzPlatform] FRITZ-WLAN-Repeater-2400-OG Led (led): An error occured during getting state!
[23.4.2022, 12:26:58] [FritzPlatform] FRITZ-WLAN-Repeater-2400-OG Led (led): connect ECONNREFUSED** 192.168.178.160:49443
[23.4.2022, 12:26:58] [FritzPlatform] [DEBUG] FRITZ-Box-7590-Repeater Led (led): GET CMD: {"xhr":"1","xhrId":"all","sid":"942326fdd554a622","page":"led"}
[23.4.2022, 12:26:58] [FritzPlatform] [DEBUG] FRITZ-Box-7590-Repeater Led (led): {"pid":"led","hide":{"shareUsb":true,"dyndns":true,"dectRdio":true,"rrd":true,"trafapp":true,"ssoSet":true,"kidLis":true,"trafapp_edit":true,"liveImg":true,"dslSet":true,"liveTv":true,"dectMoni":true,"port_edit":true,"rss":true,"dslFeed":true,"dslOv":true,"faxSet":true,"dslSpec":true,"wireguard_qrcode_txt":true,"boxExchange":true,"wireguard_qrcode_txt_edit":true,"trafprot_edit":true,"trafprio":true,"portoverview":true,"dectMoniEx":true,"shareVpn":true,"mobile":true,"dslStat":true,"provServ":true,"netCnt":true,"dslGraph":true,"kidPro":true,"dectMail":true},"timeTillLogout":"1200","time":[],"data":{"ledSettings":{"ledDisplay":"0","hasEnv":"1","dimValue":"2","canDim":"1","envLight":"1"}},"sid":"942326fdd554a622"}
[23.4.2022, 12:26:58] [FritzPlatform] [DEBUG] FRITZ-WLAN-Repeater-1750E-EG Led (led): GET CMD: {"xhr":"1","xhrId":"all","sid":"95acc1e591892f31","page":"led"}
[23.4.2022, 12:26:58] [FritzPlatform] [DEBUG] FRITZ-WLAN-Repeater-1750E-EG Led (led): {"pid":"led","hide":{"ssoSet":true,"liveTv":true},"time":[],"data":{"ledSettings":{"canDim":"0","hasEnv":"0","ledDisplay":"0"}},"sid":"95acc1e591892f31"}
[23.4.2022, 12:26:59] [FritzPlatform] [DEBUG] FRITZ-WLAN-Repeater-1750E-KG Led (led): GET CMD: {"xhr":"1","xhrId":"all","sid":"adc7245e03a84f2f","page":"led"}
[23.4.2022, 12:26:59] [FritzPlatform] [DEBUG] FRITZ-WLAN-Repeater-1750E-KG Led (led): {"pid":"led","hide":{"ssoSet":true,"liveTv":true},"time":[],"data":{"ledSettings":{"canDim":"0","hasEnv":"0","ledDisplay":"2"}},"sid":"adc7245e03a84f2f"}
[23.4.2022, 12:26:59] [FritzPlatform] [DEBUG] FRITZ-Powerline-1260E-EG Led (led): GET CMD: {"xhr":"1","xhrId":"all","sid":"8d5223e5e1e6ef40","page":"led"}

**Comment by LutzRFrank** [comment]
extended Errorlog says:

[23.4.2022, 12:33:21] [FritzPlatform] Error: connect ECONNREFUSED 192.168.178.160:49443
    at Object.exports.request (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:103:21)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at exports.requestXml (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:230:20)
    at Service.initialize (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:73:20)
    at Service.execAction (/usr/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:112:5)
    at Handler.get (/usr/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:350:28)
    at Handler.poll (/usr/lib/node_modules/homebridge-fritz-platform/src/accessories/extras/extras.handler.js:783:13) {
  title: 'No Response',
  code: 'ECONNREFUSED',
  soap: { action: 'unknown' },
  url: 'https://192.168.178.160:49443/deviceconfigSCPD.xml'
}
