### ISSUE TITLE
Wake-up call and alarm not working

### ISSUE THREAD

**Issue by Dirksteral** [SeydX/homebridge-fritz-platform#301]
**Describe the bug**
I tried to set-up a wake-up call and alarm, but I get constant errors when I trigger either of them in the Apple Home app. Protocol in Homebridge shows error (see below). 

Note: 
- On FritzBox (version 7590; Fritz OS 7.29) I created a dedicated user with all rights; I enabled call monitor
- FritzBox is in use as VoIP-system
- Non-call-related actions such as switching on/off 5ghz wifi work perfectly fine trough homebridge/Apple Home.

**To Reproduce**
1. Go to Home App
2. Click on FritzBox alarm or wake-up tile 
3. Error shows in Homebridge protocol, desired action not executed

**Expected behavior**
FritzBox should trigger alarm call to the phone number I put in fritz-platform -> extras -> alarm 
FritzBox should trigger wake-up call to internal phone number I put in fritz-platform -> extras -> wake-up

**Log**

Error: Internal Server Error
    at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:230:20)
    at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at Handler.set (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/extras/extras.handler.js:230:13) {
  title: 'Invalid Response',
  code: 500,
  soap: {
    errorCode: '501',
    errorDescription: 'Action Failed',
    action: 'urn:dslforum-org:service:X_VoIP:1#X_AVM-DE_DialNumber'
  },
  url: 'https://MYUSER:MYPASSWORD@192.168.178.1:49443/upnp/control/x_voip'
}

**Desktop (please complete the following information):**
 - OS: iPad OS 15.6.1
 - Browser Safari
 

I would be grateful for any ideas on how to solve this! Thank you!

**Comment by Dirksteral** [comment]
If someone should have the some problem: In the Fritz!Box Settings „Wählhilfe“ (dialer support) has to be activated in order for these features to work.
