### ISSUE TITLE
Fehler nach Aktivierung von DECT 440

### ISSUE THREAD

**Issue by rcei** [SeydX/homebridge-fritz-platform#302]
**Describe the bug**
Ich konnte die DECT 440 anbinden, es funktioniert auch alles wie z.B. das Datum, allerdings kriege ich alle 10 Sekunden eine Fehlermeldung wie folgt:

[FritzPlatform] TypeError: Cannot read properties of undefined (reading 'getCharacteristic')
    at Handler.get (/var/lib/homebridge/node_modules/homebridge-fritz-platform/src/accessories/smarthome/smarthome-button.handler.js:252:21)
    at Handler.poll (/var/lib/homebridge/node_modules/homebridge-fritz-platform/src/accessories/smarthome/smarthome-button.handler.js:306:20)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Expected behavior**
Sollte ohne Fehlermeldung funktionieren :)

**Hardware**
Raspberry Pi 4, B, 4GB

**Comment by TheCodingPianoman** [comment]
Das Problem beobachte ich bei meiner Homebridge-Installation auch. Die Sensorik im 440 wird korrekt ausgelesen, sprich Temperatur und Feuchtigkeit. Die Button-Anbindung ist jedoch fehlerhaft und wirft bei allen drei DECT 440 in meinem SmartHome kontinuierlich diese Meldung. 

Die Firmware auf dem DECT 440 ist in Version 5.32

**Comment by kuwagei** [comment]
Bei mir ist es ebenso. Allerdings verschwinden die Fehlermeldungen, wenn ich statt  '"buttons": 4,' nur  '"buttons": 1,' konfiguriere. Bei "buttons": none verschwindet das Gerät ganz aus HomeKit und zeigt auch Temperatur und Feuchte nicht mehr dort an.

Firmware des DECT 440 ist immer noch 5.32 , Fritz-OS 7.58 , Homebridge 1.7.0
