### ISSUE TITLE
Problem mit Fritz!DECT440: An error occured during getting state!

### ISSUE THREAD

**Issue by ghost** [SeydX/homebridge-fritz-platform#329]
Guten Morgen und schönen Sonntag,

ich sehe seit einiger Zeit diese "Fehlermeldung" im Log in Homebridge:

> [21/01/2024, 10:31:59] [FritzBox-7590-AX] DECT440 Heizungsraum (smarthome-button): An error occured during getting state!
> [21/01/2024, 10:31:59] [FritzBox-7590-AX] TypeError: Cannot read properties of undefined (reading 'getCharacteristic')
>     at Handler.get (/var/lib/homebridge/node_modules/homebridge-fritz-platform/src/accessories/smarthome/smarthome-button.handler.js:252:21)
>     at Handler.poll (/var/lib/homebridge/node_modules/homebridge-fritz-platform/src/accessories/smarthome/smarthome-button.handler.js:306:20)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)

Kann mir da Jemand weiterhelfen?

Der Fritz!DECT440 zeigt sowohl in HomeKit, als auch im Fritz!FON die korrekten Temperatur- und Luftfeuchtigkeitswerte an.

Danke schon mal,

Grüße, Andi

**Comment by MartinEmrich** [comment]
Hatte gerade das selbe Problem. Entferne den Haken bei "Battery sensor", dann kommt die Meldung nicht mehr.
