### ISSUE TITLE
Error im Log

### ISSUE THREAD

**Issue by PatrickPi1312** [SeydX/homebridge-fritz-platform#330]
Hallo ich bin Anfänger und wollte fragen wie ich diese Fehlermeldung aus dem Log bekomme 

 Error: Internal Server Error
    at Object.exports.request (/var/lib/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:78:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at exports.requestXml (/var/lib/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:230:20)
    at Service.execAction (/var/lib/homebridge/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:133:20)
    at async Promise.all (index 0)
    at Handler.get (/var/lib/homebridge/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:224:29)
    at Handler.poll (/var/lib/homebridge/node_modules/homebridge-fritz-platform/src/accessories/extras/extras.handler.js:783:13) {
  title: 'Invalid Response',
  code: 500,
  soap: {
    errorCode: '401',
    errorDescription: 'invalid action',
    action: 'urn:dslforum-org:service:WLANConfiguration:2#GetInfo'
  },
  url: 'https://admin:Marlon2019!@192.168.178.1:49443/upnp/control/wlanconfig2'
}

Danke vorab

**Comment by BKrnk1337** [comment]
Wir bräuchten den Debug-Log.

**Comment by Cali-P** [comment]
Hallo. Ich habe auch seit ein paar Tagen Probleme. Aber eigendlich nichts an meiner Netzwerk Konfiguration geändert.

Error: connect ECONNREFUSED 192.168.2.1:49443
    at Object.exports.request (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:103:21)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at exports.requestXml (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/request.js:230:20)
    at Service.initialize (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:73:20)
    at Service.execAction (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/@seydx/fritzbox/lib/service.js:112:5)
    at Handler.get (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/router/router.handler.js:323:26)
    at Handler.poll (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/extras/extras.handler.js:783:13) {
  title: 'No Response',
  code: 'ECONNREFUSED',
  soap: { action: 'unknown' },
  url: 'https://192.168.2.1:49443/x_contactSCPD.xml'

**Comment by NorbertM21** [comment]
Seit einiger Zeit bei jeder Änderung des Anwesenheitsstatus:

XXX (motion): Occupancy state changed to NOT DETECTED
This plugin generated a warning from the characteristic 'Last Activation': characteristic value expected valid finite number and received "NaN"
