### ISSUE TITLE
Error initializing plugin

### ISSUE THREAD

**Issue by ibooky-hoobs** [SeydX/homebridge-fritz-platform#338]
Hi,

i had a FritzBox 7490 Cable with which I used the plugin without any problems. After changing my setup to a 7690 Cable (Fritz OS 7.57) i can't get it running. Can anyone help? This is the Log in HOOBS 4.3.1:

7.10.2024, 12:45:58 Fritz Platform Bridge starting
7.10.2024, 12:46:02 Fritz Platform Bridge Loaded plugin 'homebridge-fritz-platform'
7.10.2024, 12:46:03 Fritz Platform Bridge FEHLER Error initializing plugin 'homebridge-fritz-platform'
7.10.2024, 12:46:03 Fritz Platform Bridge FEHLER ReferenceError: ReadableStream is not defined
at Object.<anonymous> (/var/lib/hoobs/fritzplatformbridge/node_modules/undici/lib/web/fetch/response.js:527:3)
at Module._compile (node:internal/modules/cjs/loader:1198:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
at Module.load (node:internal/modules/cjs/loader:1076:32)
at Function.Module._load (node:internal/modules/cjs/loader:911:12)
at Module.require (node:internal/modules/cjs/loader:1100:19)
at require (node:internal/modules/cjs/helpers:119:18)
at Object.<anonymous> (/var/lib/hoobs/fritzplatformbridge/node_modules/undici/lib/web/fetch/index.js:11:5)
at Module._compile (node:internal/modules/cjs/loader:1198:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1252:10)
at Module.load (node:internal/modules/cjs/loader:1076:32)
at Function.Module._load (node:internal/modules/cjs/loader:911:12)
at Module.require (node:internal/modules/cjs/loader:1100:19)
at require (node:internal/modules/cjs/helpers:119:18)
at Object.<anonymous> (/var/lib/hoobs/fritzplatformbridge/node_modules/undici/index.js:106:19)
at Module._compile (node:internal/modules/cjs/loader:1198:14)
7.10.2024, 12:46:03 Fritz Platform Bridge WARNUNG No plugins installed.
7.10.2024, 12:46:03 Fritz Platform Bridge Loading 1 platforms...
7.10.2024, 12:46:03 Fritz Platform Bridge Bridge is running on port 51876.

**Comment by ibooky-hoobs** [comment]
If anyone has an idea - every hint regarding the above error ist very much appreciated!

Thanx
-ibooky-hoobs

**Comment by ibooky-hoobs** [comment]
After installing the new FRITZ-OS update release it is now working for me. Thanks anyway!
