### ISSUE TITLE
An error occured while getting state of device led! TypeError: Cannot read property 'data' of undefined

### ISSUE THREAD

**Issue by BigKrisch** [SeydX/homebridge-fritz-platform#37]
Hey SeydX,

For some days I always get the following error message. Also a restart of all devices had unfortunately no success. 

> 2019-05-25T06:23:33.570Z FritzPlatformLUA [LUA Debug] FritzBox7580 api request 52: get /data.lua?sid=324c407f25dab2e7
2019-05-25T06:23:33.571Z FritzPlatformLUA [LUA Debug] FritzBox7580 api request 53: get /data.lua?sid=324c407f25dab2e7
2019-05-25T06:23:33.572Z FritzPlatformLUA [LUA Debug] FritzBox7580 api request 54: get /data.lua?sid=324c407f25dab2e7 (nightsetting)
2019-05-25T06:23:33.572Z FritzPlatformLUA [LUA Debug] FRITZWLAN-Repeater-1750E-KAMMERL api request 10: get /data.lua?sid=324c407f25dab2e7
2019-05-25T06:23:33.573Z FritzPlatformLUA [LUA Debug] FRITZWLAN-Repeater-1750E-ELTERN-2 api request 10: get /data.lua?sid=324c407f25dab2e7
2019-05-25T06:23:33.574Z FritzPlatformLUA [LUA Debug] FRITZWLAN-Repeater-3000-WOHNZIMMER api request 10: get /data.lua?sid=324c407f25dab2e7
2019-05-25T06:23:33.574Z FritzPlatformLUA [LUA Debug] FRITZWLAN-Repeater-1160-TANKRAUM api request 10: get /data.lua?sid=324c407f25dab2e7
2019-05-25T06:23:33.583Z FritzPlatformLUA [LUA Debug] FRITZWLAN-Repeater-1750E-KUECHE api request 10: get /data.lua?sid=324c407f25dab2e7
2019-05-25T06:23:33.584Z FritzPlatformLUA [LUA Debug] FRITZWLAN-Repeater-3000-ESSZIMMER api request 10: get /data.lua?sid=324c407f25dab2e7
2019-05-25T06:23:33.585Z FritzPlatformLUA [LUA Debug] FRITZWLAN-Repeater-1750E-ELTERN api request 10: get /data.lua?sid=324c407f25dab2e7
2019-05-25T06:23:33.747Z FritzPlatformLUA [LUA Debug] FRITZWLAN-Repeater-3000-ESSZIMMER api request 10: Requesting new SID
[2019-5-25 08:23:33] [FritzPlatform] [ERROR] FRITZWLAN-Repeater-3000-ESSZIMMER: An error occured while getting state of device led!
TypeError: Cannot read property 'data' of undefined
    at DeviceAccessory.getDeviceLED (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/device.js:883:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-05-25T06:23:33.757Z FritzPlatformLUA [LUA Debug] FRITZWLAN-Repeater-3000-WOHNZIMMER api request 10: Requesting new SID
[2019-5-25 08:23:33] [FritzPlatform] [ERROR] FRITZWLAN-Repeater-3000-WOHNZIMMER: An error occured while getting state of device led!
TypeError: Cannot read property 'data' of undefined
    at DeviceAccessory.getDeviceLED (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/device.js:883:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-05-25T06:23:33.802Z FritzPlatformLUA [LUA Debug] FRITZWLAN-Repeater-1750E-KAMMERL api request 10: Requesting new SID
[2019-5-25 08:23:33] [FritzPlatform] [ERROR] FRITZWLAN-Repeater-1750E-KAMMERL: An error occured while getting state of device led!
TypeError: Cannot read property 'data' of undefined
    at DeviceAccessory.getDeviceLED (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/device.js:883:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-05-25T06:23:33.813Z FritzPlatformLUA [LUA Debug] FRITZWLAN-Repeater-1750E-KUECHE api request 10: Requesting new SID
[2019-5-25 08:23:33] [FritzPlatform] [ERROR] FRITZWLAN-Repeater-1750E-KUECHE: An error occured while getting state of device led!
TypeError: Cannot read property 'data' of undefined
    at DeviceAccessory.getDeviceLED (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/device.js:883:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-05-25T06:23:33.834Z FritzPlatformLUA [LUA Debug] FRITZWLAN-Repeater-1750E-ELTERN api request 10: Requesting new SID
[2019-5-25 08:23:33] [FritzPlatform] [ERROR] FRITZWLAN-Repeater-1750E-ELTERN: An error occured while getting state of device led!
TypeError: Cannot read property 'data' of undefined
    at DeviceAccessory.getDeviceLED (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/device.js:883:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-05-25T06:23:33.968Z FritzPlatformLUA [LUA Debug] FRITZWLAN-Repeater-1750E-ELTERN-2 api request 10: Requesting new SID
[2019-5-25 08:23:33] [FritzPlatform] [ERROR] FRITZWLAN-Repeater-1750E-ELTERN-2: An error occured while getting state of device led!
TypeError: Cannot read property 'data' of undefined
    at DeviceAccessory.getDeviceLED (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/device.js:883:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
2019-05-25T06:23:34.012Z FritzPlatformLUA [LUA Debug] FritzBox7580 api request 52: Ok
2019-05-25T06:23:34.048Z FritzPlatformLUA [LUA Debug] FRITZWLAN-Repeater-1160-TANKRAUM api request 10: Requesting new SID
[2019-5-25 08:23:34] [FritzPlatform] [ERROR] FRITZWLAN-Repeater-1160-TANKRAUM: An error occured while getting state of device led!
TypeError: Cannot read property 'data' of undefined
    at DeviceAccessory.getDeviceLED (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/device.js:883:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)

At the same time I get Fritz! Box Log the following error message with the IP address of my Homebridge:

> 
25.05.19
08:23:35
Anmeldung an der FRITZ!Box-Benutzeroberfläche von IP-Adresse 192.168.1.109 gescheitert (ungültige Sitzungskennung). Zur Sicherheit werden alle noch gültigen Sitzungen zur IP-Adresse 192.168.1.109 beendet. [4 Meldungen seit 25.05.19 08:23:35]
25.05.19
08:23:33
[FRITZWLAN-Repeater-1750E-ELTERN-2] Anmeldung an der Benutzeroberfläche von IP-Adresse 192.168.1.109 gescheitert (ungültige Sitzungskennung). Zur Sicherheit werden alle noch gültigen Sitzungen zur IP-Adresse 192.168.1.109 beendet.
25.05.19
08:23:33
[FRITZWLAN-Repeater-1750E-ELTERN] Anmeldung an der Benutzeroberfläche von IP-Adresse 192.168.1.109 gescheitert (ungültige Sitzungskennung). Zur Sicherheit werden alle noch gültigen Sitzungen zur IP-Adresse 192.168.1.109 beendet.
25.05.19
08:23:33
[FRITZWLAN-Repeater-3000-ESSZIMMER] Anmeldung an der Benutzeroberfläche von IP-Adresse 192.168.1.109 gescheitert (ungültige Sitzungskennung). Zur Sicherheit werden alle noch gültigen Sitzungen zur IP-Adresse 192.168.1.109 beendet.

Can you please take a look at this error?

Many Thanks!

**Comment by SeydX** [comment]
hey @BigKrisch 

should be fixed with v4.0.8

**Comment by BigKrisch** [comment]
Super!  Now it works fine. 

Many thanks for the great support !!
