### ISSUE TITLE
An error occured while getting new state!

### ISSUE THREAD

**Issue by BigKrisch** [SeydX/homebridge-fritz-platform#38]
Hey SeydX,

Unfortunately I have to ask you for help again. 
Recently I get the same error message again and again and then the respective function can not be executed anymore. Even a restart of the Homebridge or the Fritz devices has not been able to fix the error.
The following error messages I get displayed again and again:

> [2019-6-6 9:10:01 PM] [FritzPlatform] [ERROR] FritzBox7580 Deflection: An error occured while getting new state!

> [2019-6-6 9:10:01 PM] [FritzPlatform] [ERROR] FritzBox7580 WifiGuest: An error occured while getting new state!

**Comment by BigKrisch** [comment]
Here is the exact error message from the debug mode:

> [6/6/2019, 11:50:56 PM] [FritzPlatform] [ERROR] FritzBox7580 Deflection: An error occured while getting new state!
2019-06-06T21:50:56.113Z FritzPlatform Error: timeout of 10000ms exceeded
    at createError (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/axios/lib/core/createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/axios/lib/adapters/http.js:217:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
[6/6/2019, 11:50:56 PM] [FritzPlatform] [ERROR] FritzBox7580 WifiGuest: An error occured while getting new state!
2019-06-06T21:50:56.133Z FritzPlatform Error: timeout of 10000ms exceeded
    at createError (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/axios/lib/core/createError.js:16:15)
    at Timeout.handleRequestTimeout [as _onTimeout] (/usr/local/lib/node_modules/homebridge-fritz-platform/node_modules/axios/lib/adapters/http.js:217:16)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)

**Comment by loxar02** [comment]
Same Problem with FritzBox 7580 and Fimrware 7.10

**Comment by loxar02** [comment]
[6/13/2019, 1:01:43 PM] [FritzPlatform] [ERROR] FRITZ!Box 7580: An error occured while checking firmware!

TypeError: Cannot read property 'split' of undefined
at DeviceAccessory.getFirmware (/usr/lib/node_modules/homebridge-fritz-platform/src/accessories/device.js:96:47)
at processTicksAndRejections (internal/process/task_queues.js:89:5)

**Comment by SeydX** [comment]
@BigKrisch 

as u can see " timeout of 10000ms exceeded" means it can not connect to FritzBox. Normally a restart of FritzBox resolves the problem. If not, try adding a new user

@loxar02 

will be fixed in the next version

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed/added in v5 (coming soon)
