### ISSUE TITLE
FRITZ!DECT Switch funktioniert nicht mehr

### ISSUE THREAD

**Issue by bernd70** [SeydX/homebridge-fritz-platform#42]
Nach dem Austausch meiner FritzBox kann ich meine FRITZ!DECT 210 Steckdose nicht mehr schalten.

Die Konfiguration ist unverändert:

"Espressomaschine": 
{
  "active": true,
  "ain": "1234567890123",
  "tempSensor": true,
  "devType": "switch"
}

Im Log kommt aber permanent der Fehler:

FritzPlatform Espressomaschine Temperature: No device with AIN: 1234567890123 found or not intialized yet!

Ich habe das Modul auch schon neu installiert und die gesamte Konfiguration neu durchlaufen. Das hat aber leider nicht geholfen.

Es sieht aber auch so aus, als würde die grundsätzliche Kommunikation mit der Fritzbox Schwierigkeiten bereiten. Zwar steht im Log die Meldung "Successfully logged in", es kommen aber auch Fehler:

FritzPlatformTR064 [TR064 Debug] FRITZ!Box 6591 Cable api request 1: Error
[6/17/2019, 9:30:58 AM] [FritzPlatform] [ERROR] Smarthome List: An error occured while generating smarthome list!
2019-06-17T09:30:58.275Z FritzPlatform Error: read ECONNRESET
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:111:27)
2019-06-17T09:30:59.296Z FritzPlatformTR064 [TR064 Debug] FRITZ!Box 6591 Cable api request 1: Error
[6/17/2019, 9:30:59 AM] [FritzPlatform] [ERROR] FritzBox: An error occured while checking firmware!
2019-06-17T09:30:59.297Z FritzPlatform Error: read ECONNRESET

Der Unterschied zwischen alter und neuer Box ist

ALT: 6590, FritzOS 7.10
Neu: 6591: FritzOX 7.04 (die neuere gibt es noch nicht...)

Welche weiteren Analysemöglichkeiten gibt es?

Grüße
Bernd

**Comment by SeydX** [comment]
@bernd70 

hast du tr064 api offen ?

https://github.com/SeydX/homebridge-fritz-platform/blob/master/docs/Installation.md

**Comment by bernd70** [comment]
Die API war aktiviert, aber ich hatte die Fritzbox noch nicht neu gestartet... :-(
Das hatte ich bei Aktivieren wohl überlesen. Jetzt funktioniert alles, wie es soll.

Grüße

**Comment by BKrnk1337** [comment]
Ich habe ein ähnliches Problem. Ich kann mich nur über `"host": "fritz.box", "port": 49000,` anmelden. Wenn ich es über die Remote-Login Adresse (sowohl IP als auch MyFritz-Adresse) versuche, dann bekomme ich den gleichen Fehler.


`[5/1/2020, 13:36:12] [FritzPlatform] [INFO] Found 5 active devices...
2020-05-01T11:36:12.318Z FritzPlatform Checking master device...
[5/1/2020, 13:36:12] [FritzPlatform] [ERROR] An error occured while checking config!
2020-05-01T11:36:12.372Z FritzPlatform Error: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)`

@SeydX Könntest du mir hier weiterhelfen?
