### ISSUE TITLE
Presence doesn't work

### ISSUE THREAD

**Issue by CloneDevil** [SeydX/homebridge-fritz-platform#59]
I set a few users by their MAC-address. (like "address": "AABBCC112233")

If I set 'anyone' to false, I see no sensor at all.
If I set 'anyone' to true, following error appears in the log and the anyone-Sensor is greyed out in Homekit. Users are still misssing.

[11/4/2019, 1:09:17 PM] [FritzPlatform] [INFO] Configuring accessory from cache: Anyone                                     
(node:364) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getHostList' of undefined                     
    at PresenceAccessory.getStates (/homebridge/node_modules/homebridge-fritz-platform/src/accessories/presence.js:62:28)   
    at PresenceAccessory.getService (/homebridge/node_modules/homebridge-fritz-platform/src/accessories/presence.js:56:10)  
    at new PresenceAccessory (/homebridge/node_modules/homebridge-fritz-platform/src/accessories/presence.js:31:10)         
    at FritzPlatform._addOrConfigure (/homebridge/node_modules/homebridge-fritz-platform/src/platform.js:453:9)             
    at FritzPlatform.configureAccessory (/homebridge/node_modules/homebridge-fritz-platform/src/platform.js:644:14)         
    at listOnTimeout (internal/timers.js:531:17)                                                                            
    at processTimers (internal/timers.js:475:7)                                                                             
(node:364) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of
 an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)  
(node:364) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that
 are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed/added in v5 (coming soon)
