### ISSUE TITLE
Error Message when trying to change status of DECT 301

### ISSUE THREAD

**Issue by rotorsim** [SeydX/homebridge-fritz-platform#65]
For a few days I'm experimenting with smart home, using homebridge and the fritz-platform plugin. Today I was surprised about the following log entry. "HZK Jakob" is a DECT 301 thermostat that was to be set to an other temperature an switches from cool to heat mode. Some hours later the same command worked without error message. 

[2020-2-4 16:15:13] [FritzPlatform] [INFO] HZK Jakob: Setting new temperature: 23
[2020-2-4 16:15:14] [FritzPlatform] [INFO] HZK Jakob: Heat Mode *
(node:4091) UnhandledPromiseRejectionWarning: Error: This callback function has already been called by someone else; it can only be called one time.
    at /usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:12:13
    at SmarthomeAccessory.setThermostatState (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/smarthome.js:468:7)
    at Characteristic.emit (events.js:223:5)
    at Characteristic.setValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Characteristic.js:321:10)
    at SmarthomeAccessory.setThermostatTemp (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/smarthome.js:502:88)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:94:5)
(node:4091) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4091) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by SeydX** [comment]
Fixed in v5 Beta 21
