### ISSUE TITLE
since update Hombridge to 1.0.0 i get thos Error "Error: The requested platform 'FritzPlatform' was not registered by any plugin."

### ISSUE THREAD

**Issue by testpaul999** [SeydX/homebridge-fritz-platform#76]
[2020-4-27 7:52:38] Error loading platform requested in your config.json at position 3
[2020-4-27 7:52:38] Error: The requested platform 'FritzPlatform' was not registered by any plugin.
    at PluginManager.getPluginForPlatform (/usr/local/lib/node_modules/homebridge/src/pluginManager.ts:223:15)
    at /usr/local/lib/node_modules/homebridge/src/server.ts:361:37
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:348:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:151:29)
    at cli (/usr/local/lib/node_modules/homebridge/src/cli.ts:74:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

**Comment by Zer0x00** [comment]
**Workaround:** Find the location of your homebridge-fritz-platform folder.

Inside the folder edit package.json:

Search for:
``"homebridge": "^0.4.49"``

Replace by:
``"homebridge": ">=0.4.49"``

**Comment by udovic2100** [comment]
@testpaul999: Did the fix provided by @Zer0x00 work for you. I'm hesitating to update to homebridge 1.0 because I'm also using the fritz-platform plugin.

**Comment by testpaul999** [comment]
Works fine for me.
