### ISSUE TITLE
Deflection is not working

### ISSUE THREAD

**Issue by dragonpil** [SeydX/homebridge-fritz-platform#80]
**Describe the bug**
Deflection is not able to get the state in the fritzbox.  I made sure that a single deflection is configured in the fritzbox. 

**To Reproduce**

I configured.... 
```
  "FRITZ!Box 5490": {
                    "active": true,
                    "host": "<ipoffritz.box>",
                    "port": 49000,
                    "username": "xxx",
                    "password": "xxxxx",
                    "type": "dsl",
                    "master": true,
                    "mesh": false,
                    "readOnly": false,
                    "options": {
                        "reconnect": true,
                        "wifi2": [
                            false,
                            false
                        ],
                        "wifi5": [
                            false,
                            false
                        ],
                        "wifiGuest": [
                            false,
                            false
                        ],
                        "wps": [
                            false,
                            false
                        ],
                        "aw": [
                            false,
                            false
                        ],
                        "deflection": [
                            true,
                            true
                        ],
                        "led": [
                            true,
                            true
                        ],
                        "lock": [
                            true,
                            true
                        ]
                    }
                }
            }
```
---
I see the switch in the home bridge but when I like to open it I get the following error in the log
```
[FritzPlatform] [ERROR] FRITZ!Box 5490 Deflection: An error occured while getting new state!
2020-05-04T15:43:07.475Z FritzPlatform Error: timeout of 50000ms exceeded
    at createError (/homebridge/node_modules/homebridge-fritz-platform/node_modules/axios/lib/core/createError.js:16:15)
    at ClientRequest.handleRequestTimeout (/homebridge/node_modules/homebridge-fritz-platform/node_modules/axios/lib/adapters/http.js:256:16)
    at Object.onceWrapper (events.js:416:28)
    at ClientRequest.emit (events.js:322:22)
    at TLSSocket.emitRequestTimeout (_http_client.js:709:9)
    at Object.onceWrapper (events.js:416:28)
    at TLSSocket.emit (events.js:322:22)
    at TLSSocket.Socket._onTimeout (net.js:479:8)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)

```
**Expected behavior**
The switch is representing the state of deflection of the fritz.box and I can activate / deactivate it. 
**fritzbox 5490:**
 - OS: 7.12
 - fiber

**homebridge:**
 - Version 1.0.4

**pluginverions **
homebridge-fritz-platform v4.1.0

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed/added in v5 (coming soon)
