### ISSUE TITLE
Presence: Error while adding Anyone

### ISSUE THREAD

**Issue by BKrnk1337** [SeydX/homebridge-fritz-platform#81]
**Describe the bug**
After adding the Anyone option in presence I got the following error message in the homebridge log.

**config.json**
`"presence": {
                "user": [
                    {
                        "active": false,
                        "name": "name",
                        "address": "_ABC_"
                    }
                ],
                "anyone": true,
                "offDelay": 90,
                "onDelay": 15,
                "ping": false
            },
`

**Error message**
```
[5/10/2020, 08:43:01] [FritzPlatform] [INFO] Adding new accessory: Anyone
(node:4513) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'getHostList' of undefined
    at PresenceAccessory.getStates (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/presence.js:62:28)
    at PresenceAccessory.getService (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/presence.js:56:10)
    at new PresenceAccessory (/usr/local/lib/node_modules/homebridge-fritz-platform/src/accessories/presence.js:31:10)
    at FritzPlatform._addOrConfigure (/usr/local/lib/node_modules/homebridge-fritz-platform/src/platform.js:453:9)
    at FritzPlatform.addAccessory (/usr/local/lib/node_modules/homebridge-fritz-platform/src/platform.js:623:10)
    at FritzPlatform._addOrRemoveDevice (/usr/local/lib/node_modules/homebridge-fritz-platform/src/platform.js:375:12)
    at FritzPlatform._initPlatform (/usr/local/lib/node_modules/homebridge-fritz-platform/src/platform.js:355:16)
    at FritzPlatform._checkConfig (/usr/local/lib/node_modules/homebridge-fritz-platform/src/platform.js:261:12)
(node:4513) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4513) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Additional context**

**Comment by SeydX** [comment]
Sorting out the issues. This issue is fixed/added in v5 (coming soon)
