### ISSUE TITLE
I cant Run Beta 5 on Hoobs Docker arm64 Image.

### ISSUE THREAD

**Issue by Trackhe** [SeydX/homebridge-fritz-platform#93]
```TypeError: this.config.devices.map is not a function
    at new FritzPlatform (/hoobs/node_modules/homebridge-fritz-platform/src/platform.js:61:25)
    at Server.loadPlatforms (/usr/src/hoobs/bridge/server.js:283:34)
    at Server.run (/usr/src/hoobs/bridge/server.js:86:18)
    at module.exports (/usr/src/hoobs/bridge/cli.js:84:12)
    at Object.<anonymous> (/usr/src/hoobs/bin/hoobs:63:81)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
```

I installed with `npm i homebridge-fritz-platform@beta` because in the docker HOOBS file dosnt run it with globaly modules.

my config is important i guess:

```
        {
            "platform": "FritzPlatform",
            "debug": true,
            "devices": {
                "Blackbox": {
                    "name": "namederbox",
                    "host": "192.168.178.1",
                    "port": 49000,
                    "username": "username",
                    "password": "pw",
                    "manufacturer": "Fritz Box",
                    "model": "7590",
                    "serialNumber": "12 ställige seriennummer",
                    "type": "dsl",
                    "master": true,
                    "readOnly": true,
                    "options": {
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "switch",
                        "wifi_guest": "switch",
                        "wps": "characteristic",
                        "aw": "characteristic",
                        "deflection": "deactivated",
                        "led": "switch",
                        "lock": "switch",
                        "broadband": "deactivated"
                    }
                }
            },
            "smarthome": {
                "name1": {
                    "active": false,
                    "ain": "number",
                    "windowSensor": false,
                    "accType": "thermostat"
                },
                "name2": {
                    "active": true,
                    "ain": "number",
                    "windowSensor": true,
                    "accType": "thermostat"
                }
            },
            "options": {
                "polling": {
                    "timer": 10,
                    "exclude": [
                        {
                            "name": "FritzBox 7590"
                        },
                        {
                            "name": "wifi_2ghz"
                        },
                        {
                            "name": "router"
                        }
                    ]
                }
            }
        },
```

**Comment by SeydX** [comment]
Your config is wrong. Please check the example config!

**Comment by Trackhe** [comment]
I use https://github.com/SeydX/homebridge-fritz-platform/blob/master/example/example-config.json as a template. What i miss?

**Comment by SeydX** [comment]
Pls read the beta thread https://github.com/SeydX/homebridge-fritz-platform/issues/92 

The config u posted is for Version below 5. 

This is for v5

https://github.com/SeydX/homebridge-fritz-platform/blob/beta/example/example-config.json

**Comment by Trackhe** [comment]
@SeydX Hab die Config angepasst jetzt mekert er aber das er keine Rechte hat obwohl in der FB der User alle Rechte geniest. bis auf internet zugriff und VPN
```
29.10.2020, 17:50:51 Loaded plugin "homebridge-fritz-platform".
29.10.2020, 17:50:53 [FritzPlatform] Callmonitor is not or not correctly set up. Skip.
29.10.2020, 17:50:53 [FritzPlatform] Telegram is not or not correctly set up. Skip.
29.10.2020, 17:50:53 [FritzPlatform] Blackbox: Configuring accessory...
29.10.2020, 17:50:53 [FritzPlatform] Blackbox Wifi 2ghz: Configuring accessory...
29.10.2020, 17:50:53 [FritzPlatform] Blackbox Wifi 5ghz: Configuring accessory...
29.10.2020, 17:50:53 [FritzPlatform] Blackbox Wifi guest: Configuring accessory...
29.10.2020, 17:50:53 [FritzPlatform] Blackbox Led: Configuring accessory...
29.10.2020, 17:50:53 [FritzPlatform] Blackbox Lock: Configuring accessory...
29.10.2020, 17:50:53 [FritzPlatform] Blackbox: Getting state (Poll)...
29.10.2020, 17:50:53 Bridge is running on port PORT.
29.10.2020, 17:50:55 [FritzPlatform] Blackbox: An error occured during getting state
29.10.2020, 17:50:55 [FritzPlatform] Error: Invalid response: 401:Unauthorized
    at Request._callback (/hoobs/node_modules/@ulfalfa/fritzbox/dist/lib/request.js:18:28)
    at Request.self.callback (/hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
29.10.2020, 17:50:55 [FritzPlatform] Blackbox Wifi 5ghz: Getting state (Poll)...
29.10.2020, 17:50:55 [FritzPlatform] Blackbox Wifi 5ghz: An error occured during getting state
29.10.2020, 17:50:55 [FritzPlatform] Error: Invalid response: 401:Unauthorized
    at Request._callback (/hoobs/node_modules/@ulfalfa/fritzbox/dist/lib/request.js:18:28)
    at Request.self.callback (/hoobs/node_modules/request/request.js:185:22)
    at Request.emit (events.js:310:20)
    at Request.<anonymous> (/hoobs/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:310:20)
    at IncomingMessage.<anonymous> (/hoobs/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:416:28)
    at IncomingMessage.emit (events.js:322:22)
    at endReadableNT (_stream_readable.js:1187:12)```

my config:
```
        {
            "platform": "FritzPlatform",
            "debug": true,
            "devices": [
                {
                    "name": "Blackbox",
                    "host": "192.168.178.1",
                    "port": 49000,
                    "username": "homebridge",
                    "password": "pw",
                    "ssl": true,
                    "tr064": true,
                    "igd": true,
                    "manufacturer": "Fritz Box",
                    "model": "7590",
                    "serialNumber": "sr number",
                    "master": true,
                    "readOnly": false,
                    "connection": "dsl",
                    "options": {
                        "wifi_2ghz": "switch",
                        "wifi_5ghz": "switch",
                        "wifi_guest": "switch",
                        "wps": "characteristic",
                        "aw": "characteristic",
                        "deflection": "deactivated",
                        "led": "switch",
                        "lock": "switch",
                        "broadband": "deactivated"
                    }
                }
            ],
            "options": {
                "presence": {
                    "anyone": true,
                    "onDelay": 30,
                    "offDelay": 90
                },
                "polling": {
                    "timer": 10,
                    "exclude": [
                        {
                            "name": "FritzBox 7590"
                        },
                        {
                            "name": "wifi_2ghz"
                        },
                        {
                            "name": "router"
                        }
                    ]
                }
            }
        }, ...
```

**Comment by SeydX** [comment]
Hm seltsam, da stimmt in der Tat was mit den Login Daten nicht

Könntest du zu Testzwecken Passwort mal ändern zb "test123" oder so und probieren?

**Comment by Trackhe** [comment]
test123 geht nicht weil zu schwach. 
Habs deshalb mit 123Vorbei probiert und das funktioniert. Danke
